#!/bin/bash
# ----------------------------------------------------------------------
# Ericsson Network IQ DWH database control script
#
# Usage: dwhdb start|stop|restart|status
#
# ----------------------------------------------------------------------
# Copyright (c) 1999 - 2007 AB Ericsson Oy  All rights reserved.
# ----------------------------------------------------------------------

unalias stop 2> /dev/null

if [ -z "$CONF_DIR" ] ; then
  echo "ERROR: CONF_DIR is not set"
  exit 1
fi

. ${CONF_DIR}/niq.rc

if [ ${LOGNAME} != "dcuser" ] ; then
    echo "This script has to be installed by dcuser"
    exit 32
fi

start() { 

  ${ADMIN_BIN}/eniq_service_start_stop.bsh -s dwhdb -a start

}

stop() {

  ${ADMIN_BIN}/eniq_service_start_stop.bsh -s dwhdb -a stop

}

status() {

  DWH_PORT=`${BIN_DIR}/iniget DWH -v PortNumber -f ${CONF_DIR}/niq.ini`
  DWH_ENG=`${BIN_DIR}/iniget DWH -v ServerName -f ${CONF_DIR}/niq.ini`
  DBA_PASSWORD=`${BIN_DIR}/iniget DB -v DBAPassword -f ${CONF_DIR}/niq.ini`

  RESP=`${ASDIR}/bin/dbping -q -c "con=dwhdb;eng=$DWH_ENG;links=tcpip{host=dwhdb;port=${DWH_PORT};dobroadcast=none;verify=no};uid=dba;pwd=${DBA_PASSWORD}" 2>&1`

  if [ $? -eq 0 ] ; then
    echo "dwhdb is running OK"
    exit 0
  else
    xPS=`ps -ef | grep asiqsrv12 | grep dwhdb`
    if [ -z "${xPS}" ] ; then
      echo "dwhdb is not running"
      exit 1
    else
      echo "dwhdb is running but does not accept requests"
      exit 2
    fi
  fi

}

case "$1" in
start)
      start
      ;;
stop)
      stop
      ;;
restart)
      stop
      start
      ;;
status)
      status
      ;;
*) 
      echo "Usage: dwhdb start|stop|restart|status"
      exit 10
      ;;
esac
