CREATE TABLE META_DATABASES (USERNAME VARCHAR(30), VERSION_NUMBER VARCHAR(32), TYPE_NAME VARCHAR(15), CONNECTION_ID NUMERIC(38), CONNECTION_NAME VARCHAR(30), CONNECTION_STRING VARCHAR(200), PASSWORD VARCHAR(30), DESCRIPTION VARCHAR(32000), DRIVER_NAME VARCHAR(100), DB_LINK_NAME VARCHAR(128));
CREATE TABLE GROUPTYPES (GROUPTYPE VARCHAR(64), VERSIONID VARCHAR(128), DATANAME VARCHAR(128), DATATYPE VARCHAR(50), DATASIZE INT, DATASCALE INT, NULLABLE INT);
CREATE TABLE GROUP_TYPE_E_APN (GROUP_NAME VARCHAR(64), START_TIME DATETIME, STOP_TIME DATETIME, APN VARCHAR(127));
CREATE TABLE GROUP_TYPE_E_TAC (GROUP_NAME VARCHAR(64), START_TIME DATETIME, STOP_TIME DATETIME, TAC INT);
CREATE TABLE GROUP_TYPE_E_IMSI (GROUP_NAME VARCHAR(64), START_TIME DATETIME, STOP_TIME DATETIME, IMSI INT);
CREATE TABLE GROUP_TYPE_E_RAT_VEND_HIER3 (GROUP_NAME VARCHAR(64), START_TIME DATETIME, STOP_TIME DATETIME, HIER3_ID INT,HIERARCHY_3 VARCHAR(64),RAT INT,VENDOR VARCHAR(64));
CREATE TABLE TPActivation(TECHPACK_NAME VARCHAR(30), STATUS VARCHAR(10), VERSIONID VARCHAR(128), TYPE VARCHAR(10), MODIFIED INT);
