insert into BUSYHOURSOURCE (VERSIONID, BHLEVEL, BHTYPE, TYPENAME, TARGETVERSIONID, BHOBJECT) values ('DC_E_BSS:((10))', 'DC_E_BSS_BSCBH', 'CP0', 'DC_E_BSS_CELL3_RAW', 'DC_E_BSS:((10))', 'BSC');
insert into BUSYHOURSOURCE (VERSIONID, BHLEVEL, BHTYPE, TYPENAME, TARGETVERSIONID, BHOBJECT) values ('DC_E_BSS:((10))', 'DC_E_BSS_BSCBH', 'PP0', 'DC_E_BSS_CELL3_RAW', 'DC_E_BSS:((10))', 'BSC');
insert into BUSYHOURSOURCE (VERSIONID, BHLEVEL, BHTYPE, TYPENAME, TARGETVERSIONID, BHOBJECT) values ('DC_E_BSS:((10))', 'DC_E_BSS_CELLBH', 'CP0', 'DC_E_BSS_CELL_ADJ_RAW', 'DC_E_BSS:((10))', 'CELL');
insert into BUSYHOURSOURCE (VERSIONID, BHLEVEL, BHTYPE, TYPENAME, TARGETVERSIONID, BHOBJECT) values ('DC_E_BSS:((10))', 'DC_E_BSS_CELLBH', 'PP0', 'DC_E_BSS_CELL2_RAW', 'DC_E_BSS:((10))', 'CELL');
