insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_BSS:((10)):DC_E_BSS_CELLBH', 'CELL');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_BSS:((10)):DC_E_BSS_BSCBH', 'BSC');
