; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Ericsson Network IQ Universe Installer
AppVerName=Ericsson Network IQ UniverseInstaller
AppPublisher=Oy L M Ericsson Ab
AppPublisherURL=http://www.ericsson.com
AppSupportURL=http://www.ericsson.com
AppUpdatesURL=http://www.ericsson.com
DisableStartupPrompt=yes
DisableReadyPage=yes
DisableFinishedPage=no
UseSetupLdr=yes
DefaultDirName={pf}\Ericsson Network IQ\Universe Installer
DisableDirPage=yes
DefaultGroupName=Ericsson Network IQ Universe Installer
DisableProgramGroupPage=yes
OutputDir=..\..\..\..\build\unv_installer\
OutputBaseFilename=universe_installer
SetupIconFile=..\..\src\ericsson.ico
Compression=lzma
SolidCompression=true
VersionInfoVersion=5.2
VersionInfoCompany=Oy L M Ericsson Ab
VersionInfoDescription=Ericsson Network IQ Universe Installer
VersionInfoCopyright=Oy L M Ericsson Ab
MinVersion=0,5.0.2195
AppCopyright=Oy L M Ericsson Ab
VersionInfoTextVersion=18.2.2008

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Files]
Source: ..\..\executable\ENIQ Universe Installer.exe; DestDir: {app}; Flags: ignoreversion
Source: ..\..\executable\Interop.Designer.dll; DestDir: {app}; Flags: ignoreversion; Attribs: hidden

[Icons]
Name: {group}\ENIQ Universe Installer; Filename: {app}\ENIQ Universe Installer.exe; WorkingDir: {app}
Name: {group}\{cm:UninstallProgram,ENIQ Universe Installer}; Filename: {uninstallexe}
