; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Ericsson Network IQ Tech Pack SDK
AppVerName=Ericsson Network IQ Tech Pack SDK
AppPublisher=Oy L M Ericsson Ab
AppPublisherURL=http://www.ericsson.com
AppSupportURL=http://www.ericsson.com
AppUpdatesURL=http://www.ericsson.com
DisableStartupPrompt=yes
DisableReadyPage=yes
DisableFinishedPage=no
UseSetupLdr=yes
DefaultDirName={pf}\Ericsson Network IQ\Tech Pack SDK
DisableDirPage=yes
DefaultGroupName=Ericsson Network IQ Tech Pack SDK
DisableProgramGroupPage=yes
OutputDir=..\..\..\..\build\tp_wizard\
OutputBaseFilename=tech_pack_sdk_setup
SetupIconFile=..\src\ericsson.ico
Compression=lzma
SolidCompression=true
VersionInfoVersion=5.3
VersionInfoCompany=Oy L M Ericsson Ab
VersionInfoDescription=Ericsson Network IQ Tech Pack SDK
VersionInfoCopyright=Oy L M Ericsson Ab
MinVersion=0,5.0.2195
AppCopyright=Oy L M Ericsson Ab
VersionInfoTextVersion=07.01.2008
AppID={{23AF809F-B9D7-48DF-8E1F-BAEA969BCF0F}

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Files]
Source: ..\executable\Metadata Wizard.exe; DestDir: {app}; Flags: ignoreversion
Source: ..\executable\Metadata Wizard.exe.config; DestDir: {app}; Flags: ignoreversion confirmoverwrite uninsneveruninstall
Source: ..\executable\Reporting Wizard.exe; DestDir: {app}; Flags: ignoreversion
Source: ..\executable\Reporting Wizard.exe.config; DestDir: {app}; Flags: ignoreversion confirmoverwrite uninsneveruninstall
Source: ..\executable\Interop.busobj.dll; DestDir: {app}; Flags: ignoreversion; Attribs: hidden
Source: ..\executable\Interop.Designer.dll; DestDir: {app}; Flags: ignoreversion; Attribs: hidden
Source: ..\executable\Interop.VBIDE.dll; DestDir: {app}; Flags: ignoreversion; Attribs: hidden
Source: ..\executable\stdole.dll; DestDir: {app}; Flags: ignoreversion; Attribs: hidden
Source: ..\executable\System.Data.dll; DestDir: {app}; Flags: ignoreversion; Attribs: hidden
Source: ..\executable\System.Data.xml; DestDir: {app}; Flags: ignoreversion; Attribs: hidden
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\definition\Verification_Template.ret; DestDir: {userdocs}\My Business Objects Documents\templates; Flags: ignoreversion
Source: ..\definition\Verification_CM_Template.ret; DestDir: {userdocs}\My Business Objects Documents\templates; Flags: ignoreversion
Source: ..\definition\Verification_BH_Template.ret; DestDir: {userdocs}\My Business Objects Documents\templates; Flags: ignoreversion
Source: ..\definition\Verification_Count_Template.ret; DestDir: {userdocs}\My Business Objects Documents\templates; Flags: ignoreversion
Source: ..\definition\TP_Reference.xslt; DestDir: {app}; Flags: ignoreversion
Source: ..\definition\TP_Description.xslt; DestDir: {app}; Flags: ignoreversion
Source: ..\definition\TP_Reference_SDIF.xslt; DestDir: {app}; Flags: ignoreversion
Source: ..\definition\TP_Description_SDIF.xslt; DestDir: {app}; Flags: ignoreversion
Source: ..\definition\Tech Pack Definition.xlt; DestDir: {app}\templates; Flags: ignoreversion
Source: ..\definition\Tech Pack Interface Definition.xlt; DestDir: {app}\templates; Flags: ignoreversion
Source: ..\definition\PM Tech Pack Base.xls; DestDir: {app}\base; Flags: ignoreversion
Source: ..\executable\Interop.Excel.dll; DestDir: {app}; Flags: ignoreversion
Source: ..\executable\Interop.Microsoft.Office.Core.dll; DestDir: {app}; Flags: ignoreversion
Source: ..\executable\Interop.Office.dll; DestDir: {app}
Source: ..\src\readme.txt; DestDir: {app}; Flags: ignoreversion

[Icons]
Name: {group}\Metadata Wizard; Filename: {app}\Metadata Wizard.exe; WorkingDir: {app}
Name: {group}\Reporting Wizard; Filename: {app}\Reporting Wizard.exe; WorkingDir: {app}; IconIndex: 0
Name: {group}\Tech Pack Definition Template; Filename: {app}\templates\Tech Pack Definition.xlt; WorkingDir: {app}; IconIndex: 0
Name: {group}\Tech Pack Interface Definition Template; Filename: {app}\templates\Tech Pack Interface Definition.xlt; WorkingDir: {app}; IconIndex: 0
Name: {group}\Read Me; Filename: {app}\readme.txt; WorkingDir: {app}; IconIndex: 0
Name: {group}\{cm:UninstallProgram,Tech Pack SDK}; Filename: {uninstallexe}

[Registry]
Root: HKLM; Subkey: Software\Microsoft\Jet\4.0\Engines\Excel; ValueType: string; ValueName: ImportMixedTypes; ValueData: Text; Languages: 
Root: HKLM; Subkey: Software\Microsoft\Jet\4.0\Engines\Excel; ValueType: dword; ValueName: TypeGuessRows; ValueData: 0
