insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((802)):DC_E_MGW_ATMPORTBH', 'ATMPORT');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((802)):DC_E_MGW_ATMPORT', 'ATMPORT');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((803)):DC_E_MGW_ATMPORTBH', 'ATMPORT');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((803)):DC_E_MGW_ATMPORT', 'ATMPORT');
