insert into dwhrep.DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS, LOADORDER) values ('EVENT_E_SGEH_GROUP_TYPE_E_APN:PLAIN', 'GROUP_TYPE_E_APN', '1970-01-01 01:00:00.0', 'ACTIVE', 0);
insert into dwhrep.DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS, LOADORDER) values ('EVENT_E_SGEH_GROUP_TYPE_E_EEIPCA:PLAIN', 'GROUP_TYPE_E_MCC_MNC', '1970-01-01 01:00:00.0', 'ACTIVE', 0);
insert into dwhrep.DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS, LOADORDER) values ('EVENT_E_SGEH_GROUP_TYPE_E_IMSI:PLAIN', 'GROUP_TYPE_E_IMSI', '1970-01-01 01:00:00.0', 'ACTIVE', 0);
insert into dwhrep.DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS, LOADORDER) values ('EVENT_E_SGEH_GROUP_TYPE_E_TAC:PLAIN', 'GROUP_TYPE_E_TAC', '1970-01-01 01:00:00.0', 'ACTIVE', 0);
