insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((803)):DC_E_MGW_AAL2APBH', 'AAL2AP');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((803)):DC_E_MGW_AAL2AP', 'AAL2AP');

insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_CPP:((123)):DC_E_CPP_VCLTP', 'VCLTP');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_CPP:((123)):DC_E_CPP_VCLTP_V', 'VCLTP');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_CPP:((123)):DC_E_CPP_AAL2AP', 'AAL2AP');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_CPP:((123)):DC_E_CPP_VCLTPBH', 'VCLTP');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_CPP:((123)):DC_E_CPP_AAL2APBH', 'AAL2AP');