package com.ericsson.netan.energyefficiency;

import com.ericsson.networkanalytics.KPIQueries;
import com.ericsson.networkanalytics.TopologyQueries;

public class EnergyEfficiencyQueries {
	
	@TopologyQueries
	public String getWCDMATopology(String OSS_ID){
		
		return "SELECT "
				+ "RNC.RNC_ID, "
				+ "RNC.RNC_NAME, "
				+ "RNC.RNC_FDN, "
				+ "RBS.RBS_FDN AS NODE_FDN, "
				+ "RBS.RBS_NAME AS NODE_NAME, "
				+ "RBS.RBS_VERSION AS NODE_VERSION, "
				+ "RBS.NEMIMVERSION AS NE_MIM_VERSION, "
				+ "RBS.managedElementType AS NODE_TYPE "
			+ "FROM "
				+ "DIM_E_RAN_RBS RBS, DIM_E_RAN_RNC RNC "
			+ "WHERE "
				+ "RNC.RNC_ID 		= RBS.RNC_ID "
				+ "AND RNC.OSS_ID 	= RBS.OSS_ID "
				+ "AND RBS.OSS_ID 	= '"+OSS_ID+"' "
				+ "AND RBS.STATUS 	= 'ACTIVE'";
		
	 }
	
	@TopologyQueries
	public String getLTETopology(String OSS_ID){
		
		return "SELECT "
				+ "ERBS_NAME AS NODE_NAME, "
				+ "ERBS_FDN AS NODE_FDN, "
				+ "ERBS_VERSION AS NODE_VERSION, "
				+ "NEMIMVERSION AS NE_MIM_VERSION, "
				+ "managedElementType AS NODE_TYPE "
			+ "FROM "
				+ "DIM_E_LTE_ERBS "
			+ "WHERE "
				+ "STATUS 		= 'ACTIVE' "
				+ "AND OSS_ID 	= '"+OSS_ID+"'";
		
	 }
	
	@TopologyQueries
	public String getGSMTopology(String OSS_ID){
		
		return "SELECT "
				+ "RADIONODE_NAME AS NODE_NAME, "
				+ "RADIONODE_FDN AS NODE_FDN, "
				+ "RADIONODE_VERSION AS NODE_VERSION "
			+ "FROM "
				+ "DIM_E_GRAN_RADIONODE "
			+ "WHERE "
				+ "STATUS 		= 'ACTIVE' "
				+ "AND OSS_ID 	= '"+OSS_ID+"'";
		
	 }
	
	
	
	@KPIQueries
	public String getNetworkEnergy(String OSS_ID, String datetime_id){
		String query = "SELECT "
				+ "ENERGY_NETWORK.NODE_TYPE, "
				+ "ENERGY_NETWORK.TIMELEVEL, "
				+ "ENERGY_NETWORK.DATETIME_ID, "
				+ "SUM(pmEnergyConsumption) AS TOTALENERGY, "
				+ "SUM(TOTALDATADOWN) AS TOTALDATADOWN, "
				+ "SUM(TOTALDATAUP) AS TOTALDATAUP, "
				+ "SUM(TOTALREPORTINGNODES) AS TOTALREPORTINGNODES, "
				+ "SUM(TOTALNODES) AS TOTALNODES "
				+ "FROM "
					+ "("
						+ "SELECT "
							+ "NODE_TYPE, "
							+ "TIMELEVEL, "
							+ "DATETIME_ID, "
							+ "ROWSTATUS, "
							+ "SUM(pmEnergyConsumption) AS pmEnergyConsumption, "
							+ "SUM(TOTALDATADOWN) AS TOTALDATADOWN, "
							+ "SUM(TOTALDATAUP) AS TOTALDATAUP "
						+ "FROM "
							+ "("
								+ "SELECT "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS, "
									+ "SUM(pmEnergyConsumption) AS pmEnergyConsumption, "
									+ "NULL AS TOTALDATADOWN, "
									+ "NULL AS TOTALDATAUP "
								+ "FROM "
									+ "DC_E_CPP_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
								+ "WHERE "
									+ "RAW.SN 				= NODE.NODE_FDN "
									+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
									+ "AND RAW.OSS_ID		= '"+OSS_ID+"' "
									+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "GROUP BY "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS "
								+ "UNION ALL "
								+ "SELECT "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS, "
									+ "SUM(pmEnergyConsumption) AS pmEnergyConsumption, "
									+ "NULL AS TOTALDATADOWN, "
									+ "NULL AS TOTALDATAUP "
								+ "FROM "
									+ "DC_E_TCU_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
								+ "WHERE "
									+ "RAW.SN 				= NODE.NODE_FDN "
									+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
									+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
									+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "GROUP BY "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS "
								+ "UNION ALL "
								+ "SELECT "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS, "
									+ "NULL AS pmEnergyConsumption, "
									+ "SUM(pmPdcpVolDlDrb) AS TOTALDATADOWN, "
									+ "SUM(pmPdcpVolUlDrb) AS TOTALDATAUP "
								+ "FROM "
									+ "DC_E_ERBS_EUTRANCELLFDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
								+ "WHERE "
									+ "RAW.SN 				= NODE.NODE_FDN "
									+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
									+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
									+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "GROUP BY "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS "
								+ "UNION ALL "
								+ "SELECT "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS, "
									+ "NULL AS pmEnergyConsumption, "
									+ "SUM(pmPdcpVolDlDrb) AS TOTALDATADOWN, "
									+ "SUM(pmPdcpVolUlDrb) AS TOTALDATAUP "
								+ "FROM "
									+ "DC_E_ERBS_EUTRANCELLTDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
								+ "WHERE "
									+ "RAW.SN 				= NODE.NODE_FDN "
									+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
									+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
									+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "GROUP BY "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS "
								+ "UNION ALL "
								+ "SELECT "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS, "
									+ "NULL AS pmEnergyConsumption, "
									+ "SUM("
										+ "pmDlTrafficVolumeAmr4750+"
										+ "pmDlTrafficVolumeAmr5900+"
										+ "pmDlTrafficVolumeAmr7950+"
										+ "pmDlTrafficVolumeAmrNbMm+"
										+ "pmDlTrafficVolumeAmrWb+"
										+ "pmDlTrafficVolumeCs12+"
										+ "pmDlTrafficVolumeCs57+"
										+ "pmDlTrafficVolumeCs64+"
										+ "pmDlTrafficVolumePs128+"
										+ "pmDlTrafficVolumePs16+"
										+ "pmDlTrafficVolumePs384+"
										+ "pmDlTrafficVolumePs64+"
										+ "pmDlTrafficVolumePs8+"
										+ "pmDlTrafficVolumePsCommon+"
										+ "pmDlTrafficVolumePsIntHs+"
										+ "pmDlTrafficVolumePsStr128+"
										+ "pmDlTrafficVolumePsStr16+"
										+ "pmDlTrafficVolumePsStr64+"
										+ "pmDlTrafficVolumePsStrHs+"
										+ "pmDlTrafficVolumeSrb136+"
										+ "pmDlTrafficVolumeSrb34+"
										+ "pmDlTrafficVolumeSrbOnlyHs) "
											+ "AS TOTALDATADOWN, "
									+ "SUM("
										+ "pmUlTrafficVolumeAmr4750+"
										+ "pmUlTrafficVolumeAmr5900+"
										+ "pmUlTrafficVolumeAmr7950+"
										+ "pmUlTrafficVolumeAmrNbMm+"
										+ "pmUlTrafficVolumeAmrWb+"
										+ "pmUlTrafficVolumeCs12+"
										+ "pmUlTrafficVolumeCs57+"
										+ "pmUlTrafficVolumeCs64+"
										+ "pmUlTrafficVolumePs128+"
										+ "pmUlTrafficVolumePs16+"
										+ "pmUlTrafficVolumePs384+"
										+ "pmUlTrafficVolumePs64+"
										+ "pmUlTrafficVolumePs8+"
										+ "pmUlTrafficVolumePsCommon+"
										+ "pmUlTrafficVolumePsIntEul+"
										+ "pmUlTrafficVolumePsIntEulFach+"
										+ "pmUlTrafficVolumePsStr128+"
										+ "pmUlTrafficVolumePsStr16+"
										+ "pmUlTrafficVolumePsStr32+"
										+ "pmUlTrafficVolumeSrb136+"
										+ "pmUlTrafficVolumeSrb34+"
										+ "pmUlTrafficVolumeSrbOnlyEul) "
											+ "AS TOTALDATAUP "
								+ "FROM "
									+ "DC_E_RAN_UCELL_RAW RAW, DIM_E_ENERGY_NODE NODE "
								+ "WHERE "
									+ "RAW.SN 				= NODE.RNC_FDN "
									+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
									+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
									+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "GROUP BY "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS "
								+ "UNION ALL "
								+ "SELECT "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS, "
									+ "NULL AS pmEnergyConsumption, "
									+ "SUM("
										+ "CELLGPRS3_DLSTRVOL+"
										+ "CELLGPRS3_DLINTBGVOL) "
											+ "AS TOTALDATADOWN, "
									+ "SUM("
										+ "CELLQOSS_VOLULSTRACC+"
										+ "CELLGPRS3_ULINTBGVOL+"
										+ "CELLEIT2_LLCVOLULEIT+"
										+ "CLDTMQOS_DTMULSTRDATA) "
											+ "AS TOTALDATAUP "
								+ "FROM "
									+ "DC_E_BSS_CELL_PS_RAW RAW, DIM_E_ENERGY_NODE NODE "
								+ "WHERE "
									+ "RAW.SN 				= NODE.NODE_FDN "
									+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
									+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
									+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "GROUP BY "
									+ "NODE.NODE_TYPE, "
									+ "RAW.TIMELEVEL, "
									+ "RAW.DATETIME_ID, "
									+ "RAW.ROWSTATUS"
							+ ") ENERGY	"
							+ "GROUP BY "
								+ "NODE_TYPE, "
								+ "TIMELEVEL, "
								+ "DATETIME_ID, "
								+ "ROWSTATUS"
						+ ") ENERGY_NETWORK, "
					+ "("
						+ "SELECT "
							+ "NODE_TYPE, "
							+ "DATETIME_ID, "
							+ "ROWSTATUS, "
							+ "SUM(TOTALREPORTINGNODES) AS TOTALREPORTINGNODES, "
							+ "SUM(TOTALNODES) AS TOTALNODES "
						+ "FROM "
						+ "("
							+ "SELECT "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS, "
								+ "COUNT(DISTINCT SN) AS TOTALREPORTINGNODES, "
								+ "NULL AS TOTALNODES "
							+ "FROM "
								+ "DC_E_TCU_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
							+ "WHERE "
								+ "RAW.SN 					= NODE.NODE_FDN "
								+ "AND RAW.OSS_ID 			= NODE.OSS_ID "
								+ "AND RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "AND  RAW.OSS_ID 			= '"+OSS_ID+"' "
								+ "AND pmEnergyConsumption IS NOT NULL "
							+ "GROUP BY "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS "
							+ "UNION ALL "
							+ "SELECT "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS, "
								+ "COUNT(DISTINCT SN) AS TOTALREPORTINGNODES, "
								+ "NULL AS TOTALNODES "
							+ "FROM "
								+ "DC_E_CPP_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
							+ "WHERE "
								+ "RAW.SN 					= NODE.NODE_FDN "
								+ "AND RAW.OSS_ID 			= NODE.OSS_ID "
								+ "AND RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "AND  RAW.OSS_ID 			= '"+OSS_ID+"' "
								+ "AND pmEnergyConsumption IS NOT NULL "
							+ "GROUP BY "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS "
							+ "UNION ALL "
							+ "SELECT "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS, "
								+ "NULL AS TOTALREPORTINGNODES, "
								+ "COUNT(DISTINCT SN) AS TOTALNODES "
							+ "FROM "
								+ "DC_E_CPP_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
							+ "WHERE "
								+ "RAW.SN 					= NODE.NODE_FDN "
								+ "AND RAW.OSS_ID 			= NODE.OSS_ID "
								+ "AND RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "AND  RAW.OSS_ID 			= '"+OSS_ID+"' "
							+ "GROUP BY "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS "
							+ "UNION ALL "
							+ "SELECT "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS, "
								+ "NULL AS TOTALREPORTINGNODES, "
								+ "COUNT(DISTINCT SN) AS TOTALNODES "
							+ "FROM "
								+ "DC_E_TCU_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
							+ "WHERE "
								+ "RAW.SN 					= NODE.NODE_FDN "
								+ "AND RAW.OSS_ID 			= NODE.OSS_ID "
								+ "AND RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "AND  RAW.OSS_ID 			= '"+OSS_ID+"' "
							+ "GROUP BY "
								+ "NODE.NODE_TYPE, "
								+ "RAW.DATETIME_ID, "
								+ "RAW.ROWSTATUS"
						+ ") REPORTING_NODES "
						+ "GROUP BY "
							+ "NODE_TYPE, "
							+ "DATETIME_ID, "
							+ "ROWSTATUS"
					+ ") TOTAL_REPORTING_NODES "
				+ "WHERE "
					+ "ENERGY_NETWORK.NODE_TYPE			=	TOTAL_REPORTING_NODES.NODE_TYPE "
					+ "AND ENERGY_NETWORK.DATETIME_ID	=	TOTAL_REPORTING_NODES.DATETIME_ID "
					+ "AND ENERGY_NETWORK.ROWSTATUS		=	TOTAL_REPORTING_NODES.ROWSTATUS "
					+ "AND ENERGY_NETWORK.ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
				+ "GROUP BY "
					+ "ENERGY_NETWORK.NODE_TYPE, "
					+ "ENERGY_NETWORK.TIMELEVEL, "
					+ "ENERGY_NETWORK.DATETIME_ID";
		
		return query;	
	}
	
	@KPIQueries
	public String getTotalEnergyPerNode(String OSS_ID, String datetime_id){
		String measureID = "1";
		
		String query = "SELECT "
				+ "NODE_ID, "
				+ "DATETIME_ID, "
				+ "TIMELEVEL, "
				+ "SUM(MEASUREVALUE) AS MEASUREVALUE "
				+ "FROM "
				+ "("
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.TIMELEVEL, "
						+ "SUM(pmEnergyConsumption) AS MEASUREVALUE "
					+ "FROM "
						+ "DC_E_CPP_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
					+ "WHERE "
						+ "RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND RAW.SN 			= NODE.NODE_FDN "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
					+ "GROUP BY "
						+ "NODE.NODE_ID, "
						+ "DATETIME_ID, "
						+ "TIMELEVEL "
					+ "UNION ALL "
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.TIMELEVEL, "
						+ "SUM(pmEnergyConsumption) AS MEASUREVALUE "
					+ "FROM "
						+ "DC_E_TCU_ENERGYMEASUREMENT_RAW RAW, DIM_E_ENERGY_NODE NODE "
					+ "WHERE "
						+ "RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND RAW.SN 			= NODE.NODE_FDN "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
					+ "GROUP BY "
						+ "NODE.NODE_ID, "
						+ "DATETIME_ID, "
						+ "TIMELEVEL "
				+ ") ENERGYPERNODE "
				+ "WHERE "
					+ "NODE_ID IN (SELECT "
								+ "DISTINCT NODE_ID "
							+ "FROM "
								+ "DIM_E_ENERGY_SEGMENT "
							+ "WHERE "
								+ "STATUS = 'ACTIVE') "
				+ "GROUP BY "
					+ "NODE_ID, "
					+ "DATETIME_ID, "
					+ "TIMELEVEL";
		
		return measureID+"-"+query;
	}
	
	@KPIQueries
	public String getTotalDataDownPerNode(String OSS_ID, String datetime_id){
		String measureID = "2";
		
		String query = "SELECT "
				+ "NODE_ID, "
				+ "TIMELEVEL, "
				+ "DATETIME_ID, "
				+ "SUM(TOTALDATADOWN) AS MEASUREVALUE "
				+ "FROM"
					+ "( "
						+ "SELECT "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS, "
							+ "SUM(pmPdcpVolDlDrb) AS TOTALDATADOWN "
						+ "FROM "
							+ "DC_E_ERBS_EUTRANCELLFDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
						+ "WHERE "
							+ "RAW.SN 				= NODE.NODE_FDN "
							+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
							+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
							+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
							+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
							+ "AND NODE_ID IN "
							+ "("
								+ "SELECT "
									+ "DISTINCT NODE_ID "
								+ "FROM "
									+ "DIM_E_ENERGY_SEGMENT "
								+ "WHERE "
									+ "STATUS = 'ACTIVE') "
						+ "GROUP BY "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS "
						+ "UNION ALL "
						+ "SELECT "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS, "
							+ "SUM(pmPdcpVolDlDrb) AS TOTALDATADOWN "
						+ "FROM "
							+ "DC_E_ERBS_EUTRANCELLTDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
						+ "WHERE "
							+ "RAW.SN 				= NODE.NODE_FDN "
							+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
							+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
							+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
							+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
							+ "AND NODE_ID IN "
							+ "("
								+ "SELECT "
									+ "DISTINCT NODE_ID "
								+ "FROM "
									+ "DIM_E_ENERGY_SEGMENT "
								+ "WHERE "
									+ "STATUS = 'ACTIVE') "
						+ "GROUP BY "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS "
						+ "UNION ALL "
						+ "SELECT "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS, "
							+ "SUM("
								+ "pmDlTrafficVolumeAmr4750+"
								+ "pmDlTrafficVolumeAmr5900+"
								+ "pmDlTrafficVolumeAmr7950+"
								+ "pmDlTrafficVolumeAmrNbMm+"
								+ "pmDlTrafficVolumeAmrWb+"
								+ "pmDlTrafficVolumeCs12+"
								+ "pmDlTrafficVolumeCs57+"
								+ "pmDlTrafficVolumeCs64+"
								+ "pmDlTrafficVolumePs128+"
								+ "pmDlTrafficVolumePs16+"
								+ "pmDlTrafficVolumePs384+"
								+ "pmDlTrafficVolumePs64+"
								+ "pmDlTrafficVolumePs8+"
								+ "pmDlTrafficVolumePsCommon+"
								+ "pmDlTrafficVolumePsIntHs+"
								+ "pmDlTrafficVolumePsStr128+"
								+ "pmDlTrafficVolumePsStr16+"
								+ "pmDlTrafficVolumePsStr64+"
								+ "pmDlTrafficVolumePsStrHs+"
								+ "pmDlTrafficVolumeSrb136+"
								+ "pmDlTrafficVolumeSrb34+"
								+ "pmDlTrafficVolumeSrbOnlyHs) "
									+ "AS TOTALDATADOWN "
						+ "FROM "
							+ "DC_E_RAN_UCELL_RAW RAW, DIM_E_ENERGY_NODE NODE, DIM_E_RAN_UCELL UCELL "
						+ "WHERE "
							+ "RAW.SN 				= NODE.RNC_FDN "
							+ "AND RAW.UTRANCELL 	= UCELL.UCELL_ID "
							+ "AND NODE.NODE_NAME 	= UCELL.RBS_ID "
							+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
							+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
							+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
							+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
							+ "AND NODE_ID IN "
							+ "("
								+ "SELECT "
									+ "DISTINCT NODE_ID "
								+ "FROM "
									+ "DIM_E_ENERGY_SEGMENT "
								+ "WHERE "
									+ "STATUS = 'ACTIVE') "
						+ "GROUP BY "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS "
						+ "UNION ALL "
						+ "SELECT "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS, "
							+ "SUM("
								+ "CELLGPRS3_DLSTRVOL+"
								+ "CELLGPRS3_DLINTBGVOL) "
									+ "AS TOTALDATADOWN "
						+ "FROM "
							+ "DC_E_BSS_CELL_PS_RAW RAW, DIM_E_ENERGY_NODE NODE "
						+ "WHERE "
							+ "RAW.SN 				= NODE.NODE_FDN "
							+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
							+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
							+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
							+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
							+ "AND NODE_ID IN "
							+ "("
							+ "SELECT "
								+ "DISTINCT NODE_ID "
							+ "FROM "
								+ "DIM_E_ENERGY_SEGMENT "
							+ "WHERE "
								+ "STATUS = 'ACTIVE') "
						+ "GROUP BY "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS"
				+ ") ENERGYPERNODE "
				+ "GROUP BY "
					+ "NODE_ID, "
					+ "TIMELEVEL, "
					+ "DATETIME_ID";
		
		return measureID+"-"+query;
	}
	
	@KPIQueries
	public String getTotalDataUpPerNode(String OSS_ID, String datetime_id){
		String measureID = "3";
		
		String query = "SELECT "
				+ "NODE_ID, "
				+ "TIMELEVEL, "
				+ "DATETIME_ID, "
				+ "SUM(TOTALDATAUP) AS MEASUREVALUE FROM"
				+ "( "
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS, "
						+ "SUM(pmPdcpVolUlDrb) AS TOTALDATAUP "
					+ "FROM "
						+ "DC_E_ERBS_EUTRANCELLFDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
					+ "WHERE "
						+ "RAW.SN 				= NODE.NODE_FDN "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
						+ "AND NODE_ID IN "
						+ "("
							+ "SELECT "
							+ "DISTINCT NODE_ID "
							+ "FROM "
							+ "DIM_E_ENERGY_SEGMENT "
							+ "WHERE STATUS = 'ACTIVE') "
					+ "GROUP BY "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS "
					+ "UNION ALL "
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS, "
						+ "SUM(pmPdcpVolUlDrb) AS TOTALDATAUP "
					+ "FROM "
						+ "DC_E_ERBS_EUTRANCELLTDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
					+ "WHERE "
						+ "RAW.SN 				= NODE.NODE_FDN "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
						+ "AND NODE_ID IN "
						+ "("
							+ "SELECT "
								+ "DISTINCT NODE_ID "
							+ "FROM "
								+ "DIM_E_ENERGY_SEGMENT "
							+ "WHERE "
								+ "STATUS = 'ACTIVE') "
					+ "GROUP BY "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS "
					+ "UNION ALL "
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS, "
						+ "SUM("
							+ "pmUlTrafficVolumeAmr4750+"
							+ "pmUlTrafficVolumeAmr5900+"
							+ "pmUlTrafficVolumeAmr7950+"
							+ "pmUlTrafficVolumeAmrNbMm+"
							+ "pmUlTrafficVolumeAmrWb+"
							+ "pmUlTrafficVolumeCs12+"
							+ "pmUlTrafficVolumeCs57+"
							+ "pmUlTrafficVolumeCs64+"
							+ "pmUlTrafficVolumePs128+"
							+ "pmUlTrafficVolumePs16+"
							+ "pmUlTrafficVolumePs384+"
							+ "pmUlTrafficVolumePs64+"
							+ "pmUlTrafficVolumePs8+"
							+ "pmUlTrafficVolumePsCommon+"
							+ "pmUlTrafficVolumePsIntEul+"
							+ "pmUlTrafficVolumePsIntEulFach+"
							+ "pmUlTrafficVolumePsStr128+"
							+ "pmUlTrafficVolumePsStr16+"
							+ "pmUlTrafficVolumePsStr32+"
							+ "pmUlTrafficVolumeSrb136+"
							+ "pmUlTrafficVolumeSrb34+"
							+ "pmUlTrafficVolumeSrbOnlyEul) "
								+ "AS TOTALDATAUP "
					+ "FROM "
						+ "DC_E_RAN_UCELL_RAW RAW, DIM_E_ENERGY_NODE NODE, DIM_E_RAN_UCELL UCELL "
					+ "WHERE "
						+ "RAW.SN 				= NODE.RNC_FDN "
						+ "AND RAW.UTRANCELL 	= UCELL.UCELL_ID "
						+ "AND NODE.NODE_NAME 	= UCELL.RBS_ID "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
						+ "AND NODE_ID IN "
						+ "("
							+ "SELECT "
								+ "DISTINCT NODE_ID "
							+ "FROM "
								+ "DIM_E_ENERGY_SEGMENT "
							+ "WHERE "
								+ "STATUS = 'ACTIVE') "
					+ "GROUP BY "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS "
					+ "UNION ALL "
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DATETIME_ID, "
						+ "RAW.ROWSTATUS, "
						+ "SUM("
							+ "CELLQOSS_VOLULSTRACC+"
							+ "CELLGPRS3_ULINTBGVOL+"
							+ "CELLEIT2_LLCVOLULEIT+"
							+ "CLDTMQOS_DTMULSTRDATA) "
								+ "AS TOTALDATAUP "
						+ "FROM "
							+ "DC_E_BSS_CELL_PS_RAW RAW, DIM_E_ENERGY_NODE NODE "
						+ "WHERE "
							+ "RAW.SN 				= NODE.NODE_FDN "
							+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
							+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
							+ "AND UTC_DATETIME_ID 	= '"+datetime_id+"' "
							+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
							+ "AND NODE_ID IN "
							+ "("
								+ "SELECT "
									+ "DISTINCT NODE_ID "
								+ "FROM "
									+ "DIM_E_ENERGY_SEGMENT "
								+ "WHERE "
									+ "STATUS = 'ACTIVE') "
						+ "GROUP BY "
							+ "NODE.NODE_ID, "
							+ "RAW.TIMELEVEL, "
							+ "RAW.DATETIME_ID, "
							+ "RAW.ROWSTATUS"
				+ ") ENERGYPERNODE "
				+ "GROUP BY "
					+ "NODE_ID, "
					+ "TIMELEVEL, "
					+ "DATETIME_ID";
		
		return measureID+"-"+query;
	}
	
	@KPIQueries
	public String getMicroTxSleepTime(String OSS_ID, String datetime_id){
		String measureID = "4";
		
		String query = "SELECT "
					+ "NODE.NODE_ID, "
					+ "ENERGYPERNODE.TIMELEVEL, "
					+ "ENERGYPERNODE.DATETIME_ID, "
					+ "100*AVG(pmMicroTxSleepTime)/(CAST(REPLACE(TIMELEVEL, 'MIN', '') AS NUMERIC(18,8))*60) AS MEASUREVALUE "
				+ "FROM "
					+ "DC_E_ERBS_SECTORCARRIER_RAW ENERGYPERNODE, DIM_E_ENERGY_NODE NODE "
				+ "WHERE "
					+ "ENERGYPERNODE.UTC_DATETIME_ID 	= '"+datetime_id+"' "
					+ "AND ENERGYPERNODE.SN 			= NODE.NODE_FDN "
					+ "AND ENERGYPERNODE.OSS_ID 		= NODE.OSS_ID "
					+ "AND ENERGYPERNODE.OSS_ID 		= '"+OSS_ID+"' "
					+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
					+ "AND NODE_ID IN "
					+ "("
						+ "SELECT "
							+ "DISTINCT NODE_ID "
						+ "FROM "
							+ "DIM_E_ENERGY_SEGMENT "
						+ "WHERE "
							+ "STATUS = 'ACTIVE') "
				+ "GROUP BY "
					+ "NODE.NODE_ID, "
					+ "ENERGYPERNODE.TIMELEVEL, "
					+ "ENERGYPERNODE.DATETIME_ID";
		
		return measureID+"-"+query;
	}
	
	@KPIQueries
	public String getEnergyPerCell(String OSS_ID, String datetime_id){
		String measureID = "5,6,7,8";
		
		String query = "SELECT "
						+ "NODE_ID, "
						+ "NODE_FDN, "
						+ "CELL_ID, "
						+ "TIMELEVEL, "
						+ "DATETIME_ID, "
						+ "100*pmMimoSleepTime/(CAST(REPLACE(TIMELEVEL, 'MIN', '') AS INT)*60)  AS MEASUREVALUE_5, "
						+ "100*pmCellSleepTime/(CAST(REPLACE(TIMELEVEL, 'MIN', '') AS INT)*60) AS MEASUREVALUE_6, "
						+ "100*pmCellDowntimeMan/(CAST(REPLACE(TIMELEVEL, 'MIN', '') AS INT)*60) AS MEASUREVALUE_7, "
						+ "100*pmCellDowntimeTps/(CAST(REPLACE(TIMELEVEL, 'MIN', '') AS INT)*60) AS MEASUREVALUE_8 "
					+ "FROM "
						+ "("
							+ "SELECT "
								+ "NODE.NODE_ID, "
								+ "NODE.NODE_FDN, "
								+ "RAW.EUTRANCELLFDD AS CELL_ID, "
								+ "RAW.TIMELEVEL, "
								+ "RAW.DATETIME_ID, "
								+ "pmMimoSleepTime, "
								+ "pmCellSleepTime, "
								+ "pmCellDowntimeMan, "
								+ "NULL AS pmCellDowntimeTps "
							+ "FROM "
								+ "DC_E_ERBS_EUTRANCELLFDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
							+ "WHERE "
								+ "UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "AND RAW.SN 		= NODE.NODE_FDN "
								+ "AND RAW.OSS_ID 	= NODE.OSS_ID "
								+ "AND RAW.OSS_ID 	= '"+OSS_ID+"' "
								+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
								+ "AND NODE_ID IN ("
													+ "SELECT "
														+ "DISTINCT NODE_ID "
													+ "FROM "
														+ "DIM_E_ENERGY_SEGMENT "
													+ "WHERE "
														+ "STATUS = 'ACTIVE') "
							+ "UNION ALL "
							+ "SELECT "
								+ "NODE.NODE_ID, "
								+ "NODE.NODE_FDN, "
								+ "RAW.EUTRANCELLTDD AS CELL_ID, "
								+ "RAW.TIMELEVEL, "
								+ "RAW.DATETIME_ID, "
								+ "pmMimoSleepTime, "
								+ "pmCellSleepTime, "
								+ "pmCellDowntimeMan, "
								+ "NULL AS pmCellDowntimeTps "
							+ "FROM "
								+ "DC_E_ERBS_EUTRANCELLTDD_RAW RAW, DIM_E_ENERGY_NODE NODE "
							+ "WHERE "
								+ "UTC_DATETIME_ID 	= '"+datetime_id+"' "
								+ "AND RAW.SN 		= NODE.NODE_FDN "
								+ "AND RAW.OSS_ID 	= NODE.OSS_ID "
								+ "AND RAW.OSS_ID 	= '"+OSS_ID+"' "
								+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
								+ "AND NODE_ID IN ("
													+ "SELECT "
														+ "DISTINCT NODE_ID "
													+ "FROM "
														+ "DIM_E_ENERGY_SEGMENT "
													+ "WHERE "
														+ "STATUS = 'ACTIVE') "
							+ "UNION ALL "
							+ "SELECT "
								+ "NODE.NODE_ID, "
								+ "NODE.NODE_FDN, "
								+ "RAW.UTRANCELL AS CELL_ID, "
								+ "RAW.TIMELEVEL, "
								+ "RAW.DATETIME_ID, "
								+ "NULL AS pmMimoSleepTime, "
								+ "NULL AS PMCELLSLEEPTIME, "
								+ "PMCELLDOWNTIMEMAN, "
								+ "PMCELLDOWNTIMETPS "
							+ "FROM "
								+ "DC_E_RAN_UCELL_RAW RAW, DIM_E_ENERGY_NODE NODE, DIM_E_RAN_UCELL UCELL "
							+ "WHERE "
								+ "UTC_DATETIME_ID 		= '"+datetime_id+"' "
								+ "AND RAW.SN 			= NODE.RNC_FDN "
								+ "AND RAW.UTRANCELL 	= UCELL.UCELL_ID "
								+ "AND NODE.NODE_NAME 	= UCELL.RBS_ID "
								+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
								+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
								+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
								+ "AND NODE_ID IN ("
													+ "SELECT "
														+ "DISTINCT NODE_ID "
													+ "FROM "
														+ "DIM_E_ENERGY_SEGMENT "
													+ "WHERE "
														+ "STATUS = 'ACTIVE')"
					+ ") ENERGYPERCELL";
				
		return measureID+"-"+query;
	}
	
	
	@KPIQueries
	public String getPowerConsumption(String OSS_ID, String datetime_id){
		String query = "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DCVECTOR_INDEX, "
						+ "RAW.DATETIME_ID, "
						+ "EQUIPMENTSUPPORTFUNCTION, "
						+ "ENERGYMEASUREMENT, "
						+ "pmPowerConsumption AS POWERCONSUMPTION "
					+ "FROM "
						+ "DC_E_CPP_ENERGYMEASUREMENT_V_RAW RAW, DIM_E_ENERGY_NODE NODE "
					+ "WHERE "
						+ "RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND RAW.SN 			= NODE.NODE_FDN "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
						+ "AND NODE_ID IN ("
											+ "SELECT "
												+ "DISTINCT NODE_ID "
											+ "FROM "
												+ "DIM_E_ENERGY_SEGMENT "
											+ "WHERE "
												+ "STATUS = 'ACTIVE')"
					+ "UNION ALL "
					+ "SELECT "
						+ "NODE.NODE_ID, "
						+ "RAW.TIMELEVEL, "
						+ "RAW.DCVECTOR_INDEX, "
						+ "RAW.DATETIME_ID, "
						+ "EQUIPMENTSUPPORTFUNCTION, "
						+ "ENERGYMEASUREMENT, "
						+ "pmPowerConsumption AS POWERCONSUMPTION "
					+ "FROM "
						+ "DC_E_TCU_ENERGYMEASUREMENT_V_RAW RAW, DIM_E_ENERGY_NODE NODE "
					+ "WHERE "
						+ "RAW.UTC_DATETIME_ID 	= '"+datetime_id+"' "
						+ "AND RAW.SN 			= NODE.NODE_FDN "
						+ "AND RAW.OSS_ID 		= NODE.OSS_ID "
						+ "AND RAW.OSS_ID 		= '"+OSS_ID+"' "
						+ "AND ROWSTATUS NOT IN ('DUPLICATE','SUSPECTED') "
						+ "AND NODE_ID IN ("
											+ "SELECT "
												+ "DISTINCT NODE_ID "
											+ "FROM "
												+ "DIM_E_ENERGY_SEGMENT "
											+ "WHERE "
												+ "STATUS = 'ACTIVE')";
				
		return query;
	}
	
	

}
