var C39=
"<div id=\"content\" class=\"body-content\">\n"+
"<h1 class=\"reference\"><span class=\"CHAPTITLE\"><a name=\"CHAPTER39\" href='javascript:parent.parent.sC2(\"TOP\")' class=\"CHAPLINK\">Reference List</a></span></h1>\n" +
"<table><tr><th class=\"rf-subsection\"></th></tr><tr><td><a name=\"rf-OSSGlossary\"></a>[1] <i class=\"rf-title\">Operations Support System (OSS) Glossary</i>, <!--@doc-no-->0033-AOM 901 017/2, available in the Ericsson Network IQ Statistics\n" +
"library<!--@/doc-no--></td></tr><tr><td><a name=\"rf-TypographicConventions\"></a>[2] <i class=\"rf-title\">OSS Library Typographic Conventions</i>, <!--@doc-no-->1/154 43-AOM 901 017/4, available in the Ericsson Network\n" +
"IQ Statistics library<!--@/doc-no--></td></tr><tr><td><a name=\"NetworkAnalyticserver\"></a>[3] <i class=\"rf-title\">Network Analytics Server Deployment Description, 155 34-CNA\n" +
"403 2940</i></td></tr><tr><td><a name=\"NetAnServerSAG\"></a>[4] <i class=\"rf-title\"> Network Analytics Server System Administrator Guide , 1/1543-CNA\n" +
"403 2940</i></td></tr><tr><td><a name=\"rf-BO\"></a>[5] <i class=\"rf-title\">Business Objects Documentation</i>, <!--@doc-no-->See CPI store under 3PP Documents, available in the Ericsson\n" +
"Network IQ Statistics library .<!--@/doc-no--></td></tr><tr><td><a name=\"rf-ENIQUG\"></a>[6] <i class=\"rf-title\">Ericsson Network IQ Web Portal User Guide</i>, <!--@doc-no-->1/1553-CSA 113 63/1, available in the Ericsson Network IQ\n" +
"Statistics library<!--@/doc-no--></td></tr><tr><td><a name=\"EBRDocument\"></a>[7] <i class=\"rf-title\">ENIQ Backup and Restore  System Administrator Guide</i>, <!--@doc-no-->1543-CNA 403 1964, available in the Ericsson Network IQ Statistics\n" +
"library<!--@/doc-no--></td></tr><tr><td><a name=\"EniqUpgradeProc\"></a>[8] <i class=\"rf-title\">ENIQ Statistics X86 Blade Upgrade Procedure</i>, <!--@doc-no-->35/153 72-CXP 901 9948<!--@/doc-no--></td></tr><tr><td><a name=\"ossrcsag\"></a>[9] <i class=\"rf-title\">OSS-RC System Administration Guide</i>, <!--@doc-no-->1543-AOM 901 070<!--@/doc-no--></td></tr><tr><td><a name=\"OssRCNEcommissioning\"></a>[10] <i class=\"rf-title\">OSS-RC Network Element Commissioning</i>, <!--@doc-no-->1546-AOM 901 065<!--@/doc-no--></td></tr><tr><td><a name=\"MSwebsite\"></a>[11] <i class=\"rf-title\">Microsoft</i>. <a href=\"http://www.microsoft.com\" target=\"ALEX_EXTERNAL\">http://www.microsoft.com</a><!--@/doc-no--></td></tr><tr><td><a name=\"Javawebsite\"></a>[12] <i class=\"rf-title\">Java</i>. <a href=\"http://www.java.com\" target=\"ALEX_EXTERNAL\">http://www.java.com</a><!--@/doc-no--></td></tr><tr><td><a name=\"Sybasewebsite\"></a>[13] <i class=\"rf-title\">SAP</i>. <a href=\"http://www.sap.com/\" target=\"ALEX_EXTERNAL\">http://www.sap.com/</a><!--@/doc-no--></td></tr><tr><td><a name=\"rf-IMSNodeCom\"></a>[14] <i class=\"rf-title\">OSS-RC IMS/IMT Node Commissioning</i>, <!--@doc-no-->1/1546-AOM 901 065<!--@/doc-no--></td></tr><tr><td><a name=\"BCGUserGuide\"></a>[15] <i class=\"rf-title\">BCG User Guide</i>, <!--@doc-no-->3/1553-APR 901 0403<!--@/doc-no--></td></tr><tr><td><a name=\"ReportDevelopersGuideRef\"></a>[16] <i class=\"rf-title\">ENIQ, Ericsson Network IQ Report Developer Guide</i>, <!--@doc-no-->1553-CRA 119 1037<!--@/doc-no--></td></tr><tr><td>[17] <i class=\"rf-title\"><a name=\"emmaSAG\"></a> EBID, Ericsson Business Intelligence Deployment\n" +
"Description</i>, <!--@doc-no--> 155 34 &ndash; CNA 4031452<!--@/doc-no--></td></tr><tr><td><a name=\"Ebidinstall\"></a>[18] <i class=\"rf-title\">Ericsson Business Intelligence Deployment (EBID) Installation\n" +
"and Upgrade Instructions</i>, <!--@doc-no-->1/1531-CNA 403 1452<!--@/doc-no--></td></tr><tr><td><a name=\"solarzfssag\"></a>[19] <i class=\"rf-title\">Solaris ZFS Administration Guide</i>, <!--@doc-no-->819-5461<!--@/doc-no--></td></tr><tr><td><a name=\"blade-ii-overview\"></a>[20] <i class=\"rf-title\">ENIQ Statistics Installation Overview (Blade)</i> <!--@doc-no-->1/2311-CXP 901 9948<!--@/doc-no--></td></tr><tr><td><a name=\"bladeinstall\"></a>[21] <i class=\"rf-title\">ENIQ Statistics Blade Installation Instructions</i>, <!--@doc-no-->14/1531-CXP 901 9948<!--@/doc-no--></td></tr><tr><td><a name=\"eniq-rack-ii\"></a>[22] <i class=\"rf-title\">ENIQ Statistics Rack Installation Instructions</i>, <!--@doc-no-->1/1531-CXP 901 9948<!--@/doc-no--></td></tr><tr><td><a name=\"OSSRCConfigForEniq\"></a>[23] <i class=\"rf-title\">OSS-RC Configuration for ENIQ</i>, <!--@doc-no-->1/1546-AOM 901 076<!--@/doc-no--></td></tr><tr><td>[24] <i class=\"rf-title\">ENIQ Events Configuration for ENIQ Statistics</i>, <!--@doc-no-->1/12701-AOM 901 076 Uen<!--@/doc-no--></td></tr><tr><td><a name=\"LTERANLoadExpert\"></a>[25] <i class=\"rf-title\">LTE RAN Load Expert KPI Configuration System Administrator\n" +
"Guide</i>, <!--@doc-no-->1543-COA 252 456<!--@/doc-no--></td></tr><tr><td><a name=\"RackUpgradeProcedure\"></a>[26] <i class=\"rf-title\">ENIQ Statistics Rack Upgrade Procedure</i>, <!--@doc-no-->36/15372-CXP 901 9948<!--@/doc-no--></td></tr><tr><td><a name=\"mws\"></a>[27] <i class=\"rf-title\">Management Workstation System Administration Guide</i>, <!--@doc-no-->3/1543-AOM 901 071<!--@/doc-no--></td></tr><tr><td><a name=\"OSSChangePassword\"></a>[28] <i class=\"rf-title\">Overall Security Administration in OSS-RC</i>, <!--@doc-no-->3/1543-APR 901 911<!--@/doc-no--></td></tr><tr><td><a name=\"FRHInstallInstruction\"></a>[29] <i class=\"rf-title\">FRH Installation Instructions</i>, <!--@doc-no-->47/15372-CXP 9019948<!--@/doc-no--></td></tr><tr><td><a name=\"TSSsystemAdminGuide\"></a>[30] <i class=\"rf-title\">Telecom Security Services, TSS, System Administrator Guide</i>, <!--@doc-no-->1543-APR 901 0003<!--@/doc-no--></td></tr></table>\n"+
"</div>\n";

