insert into DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS) values ('EVENT_E_SGEH_GROUP_TYPE_E_APN:PLAIN', 'GROUP_TYPE_E_APN', '1970-01-01 01:00:00.0', 'ACTIVE');
insert into DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS) values ('EVENT_E_SGEH_GROUP_TYPE_E_EEIPCA:PLAIN', 'GROUP_TYPE_E_MCC_MNC', '1970-01-01 01:00:00.0', 'ACTIVE');
insert into DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS) values ('EVENT_E_SGEH_GROUP_TYPE_E_IMSI:PLAIN', 'GROUP_TYPE_E_IMSI', '1970-01-01 01:00:00.0', 'ACTIVE');
insert into DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS) values ('EVENT_E_SGEH_GROUP_TYPE_E_TAC:PLAIN', 'GROUP_TYPE_E_TAC', '1970-01-01 01:00:00.0', 'ACTIVE');
insert into DWHPARTITION (STORAGEID, TABLENAME, STARTTIME, STATUS) values ('EVENT_E_SGEH_GROUP_TYPE_E_RAT_VEND_HIER3:PLAIN', 'GROUP_TYPE_E_RAT_VEND_HIER3', '1970-01-01 01:00:00.0', 'ACTIVE');
