//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for CapabilitiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CapabilitiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alignedReportingPeriod" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="JobPersistence" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NONE"/>
 *               &lt;enumeration value="RESTART"/>
 *               &lt;enumeration value="UPGRADE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FileRetention" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="FileCompression" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CounterCapabilities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OutputFormat" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="3GPP_XML"/>
 *                         &lt;enumeration value="3GPP_ASN.1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="OutputVersion" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="32.104 V3.5.0"/>
 *                         &lt;enumeration value="32.435 V7.2.0 "/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FileDeliveryProtocol" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="SFTP"/>
 *                         &lt;enumeration value="FTP"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FileDeliveryMethod" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="PUSH"/>
 *                         &lt;enumeration value="PULL"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DeliveryTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GranularityPeriod" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="15"/>
 *                         &lt;enumeration value="30"/>
 *                         &lt;enumeration value="60"/>
 *                         &lt;enumeration value="720"/>
 *                         &lt;enumeration value="1440"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ReportingPeriod" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="15"/>
 *                         &lt;enumeration value="30"/>
 *                         &lt;enumeration value="60"/>
 *                         &lt;enumeration value="720"/>
 *                         &lt;enumeration value="1440"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapabilitiesType", propOrder = {
    "alignedReportingPeriod",
    "jobPersistence",
    "fileRetention",
    "fileCompression",
    "counterCapabilities"
})
public class CapabilitiesType {

    @XmlElement(defaultValue = "true")
    protected String alignedReportingPeriod;
    @XmlElement(name = "JobPersistence", defaultValue = "RESTART")
    protected String jobPersistence;
    @XmlElement(name = "FileRetention", defaultValue = "24")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer fileRetention;
    @XmlElement(name = "FileCompression", defaultValue = "true")
    protected Boolean fileCompression;
    @XmlElement(name = "CounterCapabilities", required = true)
    protected CapabilitiesType.CounterCapabilities counterCapabilities;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the alignedReportingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlignedReportingPeriod() {
        return alignedReportingPeriod;
    }

    /**
     * Sets the value of the alignedReportingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlignedReportingPeriod(String value) {
        this.alignedReportingPeriod = value;
    }

    /**
     * Gets the value of the jobPersistence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobPersistence() {
        return jobPersistence;
    }

    /**
     * Sets the value of the jobPersistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobPersistence(String value) {
        this.jobPersistence = value;
    }

    /**
     * Gets the value of the fileRetention property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFileRetention() {
        return fileRetention;
    }

    /**
     * Sets the value of the fileRetention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFileRetention(Integer value) {
        this.fileRetention = value;
    }

    /**
     * Gets the value of the fileCompression property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFileCompression() {
        return fileCompression;
    }

    /**
     * Sets the value of the fileCompression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFileCompression(Boolean value) {
        this.fileCompression = value;
    }

    /**
     * Gets the value of the counterCapabilities property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilitiesType.CounterCapabilities }
     *     
     */
    public CapabilitiesType.CounterCapabilities getCounterCapabilities() {
        return counterCapabilities;
    }

    /**
     * Sets the value of the counterCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilitiesType.CounterCapabilities }
     *     
     */
    public void setCounterCapabilities(CapabilitiesType.CounterCapabilities value) {
        this.counterCapabilities = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OutputFormat" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="3GPP_XML"/>
     *               &lt;enumeration value="3GPP_ASN.1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="OutputVersion" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="32.104 V3.5.0"/>
     *               &lt;enumeration value="32.435 V7.2.0 "/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FileDeliveryProtocol" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="SFTP"/>
     *               &lt;enumeration value="FTP"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FileDeliveryMethod" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="PUSH"/>
     *               &lt;enumeration value="PULL"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DeliveryTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GranularityPeriod" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="15"/>
     *               &lt;enumeration value="30"/>
     *               &lt;enumeration value="60"/>
     *               &lt;enumeration value="720"/>
     *               &lt;enumeration value="1440"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ReportingPeriod" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="15"/>
     *               &lt;enumeration value="30"/>
     *               &lt;enumeration value="60"/>
     *               &lt;enumeration value="720"/>
     *               &lt;enumeration value="1440"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outputFormat",
        "outputVersion",
        "fileDeliveryProtocol",
        "fileDeliveryMethod",
        "deliveryTarget",
        "granularityPeriod",
        "reportingPeriod"
    })
    public static class CounterCapabilities {

        @XmlElement(name = "OutputFormat", defaultValue = "3GPP_XML")
        protected String outputFormat;
        @XmlElement(name = "OutputVersion", defaultValue = "32.104 V3.5.0")
        protected String outputVersion;
        @XmlElement(name = "FileDeliveryProtocol", defaultValue = "SFTP")
        protected String fileDeliveryProtocol;
        @XmlElement(name = "FileDeliveryMethod")
        protected String fileDeliveryMethod;
        @XmlElement(name = "DeliveryTarget", required = true, defaultValue = "\"\"")
        protected String deliveryTarget;
        @XmlElement(name = "GranularityPeriod", defaultValue = "15")
        protected Long granularityPeriod;
        @XmlElement(name = "ReportingPeriod", defaultValue = "15")
        protected Long reportingPeriod;

        /**
         * Gets the value of the outputFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputFormat() {
            return outputFormat;
        }

        /**
         * Sets the value of the outputFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputFormat(String value) {
            this.outputFormat = value;
        }

        /**
         * Gets the value of the outputVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputVersion() {
            return outputVersion;
        }

        /**
         * Sets the value of the outputVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputVersion(String value) {
            this.outputVersion = value;
        }

        /**
         * Gets the value of the fileDeliveryProtocol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileDeliveryProtocol() {
            return fileDeliveryProtocol;
        }

        /**
         * Sets the value of the fileDeliveryProtocol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileDeliveryProtocol(String value) {
            this.fileDeliveryProtocol = value;
        }

        /**
         * Gets the value of the fileDeliveryMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileDeliveryMethod() {
            return fileDeliveryMethod;
        }

        /**
         * Sets the value of the fileDeliveryMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileDeliveryMethod(String value) {
            this.fileDeliveryMethod = value;
        }

        /**
         * Gets the value of the deliveryTarget property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryTarget() {
            return deliveryTarget;
        }

        /**
         * Sets the value of the deliveryTarget property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryTarget(String value) {
            this.deliveryTarget = value;
        }

        /**
         * Gets the value of the granularityPeriod property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getGranularityPeriod() {
            return granularityPeriod;
        }

        /**
         * Sets the value of the granularityPeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setGranularityPeriod(Long value) {
            this.granularityPeriod = value;
        }

        /**
         * Gets the value of the reportingPeriod property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getReportingPeriod() {
            return reportingPeriod;
        }

        /**
         * Sets the value of the reportingPeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setReportingPeriod(Long value) {
            this.reportingPeriod = value;
        }

    }

}
