//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for counterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="counterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="measurementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectionMethod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="CC"/>
 *                         &lt;enumeration value="SI"/>
 *                         &lt;enumeration value="GAUGE"/>
 *                         &lt;enumeration value="DER"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="subtype">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="MIN"/>
 *                         &lt;enumeration value="MAX"/>
 *                         &lt;enumeration value="LAST_UPDATE"/>
 *                         &lt;enumeration value="RAW"/>
 *                         &lt;enumeration value="MEAN"/>
 *                         &lt;enumeration value="SUM"/>
 *                         &lt;enumeration value=""/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="measurementResult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="outputUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="resultType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="float"/>
 *                         &lt;enumeration value="integer"/>
 *                         &lt;enumeration value="numeric"/>
 *                         &lt;enumeration value="int"/>
 *                         &lt;enumeration value="tinyint"/>
 *                         &lt;enumeration value="smallint"/>
 *                         &lt;enumeration value="unsigned int"/>
 *                         &lt;enumeration value="long"/>
 *                         &lt;enumeration value="double"/>
 *                         &lt;enumeration value="dateTime"/>
 *                         &lt;enumeration value="date"/>
 *                         &lt;enumeration value="char"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="current"/>
 *               &lt;enumeration value="obsolete"/>
 *               &lt;enumeration value="deprecated"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cpiHeading" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="cardinality" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="std3GPPmeasurementType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keyTypeName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="alarm" type="{com:ericsson:ims:mim}alarmType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="measurementType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "counterType", propOrder = {
    "measurementName",
    "description",
    "condition",
    "collectionMethod",
    "measurementResult",
    "status",
    "cpiHeading",
    "cardinality",
    "std3GPPmeasurementType",
    "keyTypeName",
    "alarm"
})
public class CounterType {

    @XmlElement(required = true)
    protected String measurementName;
    @XmlElement(required = true, defaultValue = "\"\"")
    protected String description;
    @XmlElement(required = true, defaultValue = "\"\"")
    protected String condition;
    @XmlElement(required = true)
    protected CounterType.CollectionMethod collectionMethod;
    @XmlElement(required = true)
    protected CounterType.MeasurementResult measurementResult;
    @XmlElement(required = true, defaultValue = "current")
    protected String status;
    @XmlElement(required = true)
    protected Object cpiHeading;
    @XmlElement(required = true)
    protected BigInteger cardinality;
    @XmlElement(required = true)
    protected String std3GPPmeasurementType;
    protected List<String> keyTypeName;
    protected AlarmType alarm;
    @XmlAttribute(required = true)
    protected String measurementType;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the measurementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementName() {
        return measurementName;
    }

    /**
     * Sets the value of the measurementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementName(String value) {
        this.measurementName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the collectionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CounterType.CollectionMethod }
     *     
     */
    public CounterType.CollectionMethod getCollectionMethod() {
        return collectionMethod;
    }

    /**
     * Sets the value of the collectionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterType.CollectionMethod }
     *     
     */
    public void setCollectionMethod(CounterType.CollectionMethod value) {
        this.collectionMethod = value;
    }

    /**
     * Gets the value of the measurementResult property.
     * 
     * @return
     *     possible object is
     *     {@link CounterType.MeasurementResult }
     *     
     */
    public CounterType.MeasurementResult getMeasurementResult() {
        return measurementResult;
    }

    /**
     * Sets the value of the measurementResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterType.MeasurementResult }
     *     
     */
    public void setMeasurementResult(CounterType.MeasurementResult value) {
        this.measurementResult = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the cpiHeading property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCpiHeading() {
        return cpiHeading;
    }

    /**
     * Sets the value of the cpiHeading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCpiHeading(Object value) {
        this.cpiHeading = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardinality(BigInteger value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the std3GPPmeasurementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStd3GPPmeasurementType() {
        return std3GPPmeasurementType;
    }

    /**
     * Sets the value of the std3GPPmeasurementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStd3GPPmeasurementType(String value) {
        this.std3GPPmeasurementType = value;
    }

    /**
     * Gets the value of the keyTypeName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyTypeName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyTypeName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeyTypeName() {
        if (keyTypeName == null) {
            keyTypeName = new ArrayList<String>();
        }
        return this.keyTypeName;
    }

    /**
     * Gets the value of the alarm property.
     * 
     * @return
     *     possible object is
     *     {@link AlarmType }
     *     
     */
    public AlarmType getAlarm() {
        return alarm;
    }

    /**
     * Sets the value of the alarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlarmType }
     *     
     */
    public void setAlarm(AlarmType value) {
        this.alarm = value;
    }

    /**
     * Gets the value of the measurementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementType() {
        return measurementType;
    }

    /**
     * Sets the value of the measurementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementType(String value) {
        this.measurementType = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CC"/>
     *               &lt;enumeration value="SI"/>
     *               &lt;enumeration value="GAUGE"/>
     *               &lt;enumeration value="DER"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="subtype">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MIN"/>
     *               &lt;enumeration value="MAX"/>
     *               &lt;enumeration value="LAST_UPDATE"/>
     *               &lt;enumeration value="RAW"/>
     *               &lt;enumeration value="MEAN"/>
     *               &lt;enumeration value="SUM"/>
     *               &lt;enumeration value=""/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "subtype"
    })
    public static class CollectionMethod {

        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String subtype;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the subtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubtype() {
            return subtype;
        }

        /**
         * Sets the value of the subtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubtype(String value) {
            this.subtype = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="outputUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="resultType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="float"/>
     *               &lt;enumeration value="integer"/>
     *               &lt;enumeration value="numeric"/>
     *               &lt;enumeration value="int"/>
     *               &lt;enumeration value="tinyint"/>
     *               &lt;enumeration value="smallint"/>
     *               &lt;enumeration value="unsigned int"/>
     *               &lt;enumeration value="long"/>
     *               &lt;enumeration value="double"/>
     *               &lt;enumeration value="dateTime"/>
     *               &lt;enumeration value="date"/>
     *               &lt;enumeration value="char"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outputUnit",
        "resultType"
    })
    public static class MeasurementResult {

        @XmlElement(required = true)
        protected String outputUnit;
        @XmlElement(required = true)
        protected String resultType;

        /**
         * Gets the value of the outputUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputUnit() {
            return outputUnit;
        }

        /**
         * Sets the value of the outputUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputUnit(String value) {
            this.outputUnit = value;
        }

        /**
         * Gets the value of the resultType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultType() {
            return resultType;
        }

        /**
         * Sets the value of the resultType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultType(String value) {
            this.resultType = value;
        }

    }

}
