//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="moc" type="{com:ericsson:ims:mim}mocType" maxOccurs="unbounded"/>
 *         &lt;element name="keyTypesList" type="{com:ericsson:ims:mim}keyTypesListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataType", propOrder = {
    "moc",
    "keyTypesList"
})
@XmlSeeAlso({
    com.ericsson.ims.mim.PM.Data.class
})
public class DataType {

    @XmlElement(required = true)
    protected List<MocType> moc;
    @XmlElement(required = true)
    protected KeyTypesListType keyTypesList;

    /**
     * Gets the value of the moc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MocType }
     * 
     * 
     */
    public List<MocType> getMoc() {
        if (moc == null) {
            moc = new ArrayList<MocType>();
        }
        return this.moc;
    }

    /**
     * Gets the value of the keyTypesList property.
     * 
     * @return
     *     possible object is
     *     {@link KeyTypesListType }
     *     
     */
    public KeyTypesListType getKeyTypesList() {
        return keyTypesList;
    }

    /**
     * Sets the value of the keyTypesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyTypesListType }
     *     
     */
    public void setKeyTypesList(KeyTypesListType value) {
        this.keyTypesList = value;
    }

}
