//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for imsPmConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="imsPmConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="scanFile" type="{com:ericsson:ims:mim}scanFileType"/>
 *         &lt;element name="nPMFConfig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pmApplication">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="reportingRootDirectory">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="maxMonitorNr">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="500"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="measReaderNr">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="timeZone">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="utc"/>
 *                                   &lt;enumeration value="local"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="maxPmdbMemSize">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                                   &lt;minInclusive value="4"/>
 *                                   &lt;maxInclusive value="64"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="maxPmdbCpuLoad">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                                   &lt;minInclusive value="0.1"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="maxAlarmPerMeasType">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *                                   &lt;minInclusive value="3"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="monitorGroup" type="{com:ericsson:ims:mim}monitorGroupType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imsPmConfigType", propOrder = {
    "scanFile",
    "npmfConfig"
})
public class ImsPmConfigType {

    protected ScanFileType scanFile;
    @XmlElement(name = "nPMFConfig")
    protected ImsPmConfigType.NPMFConfig npmfConfig;

    /**
     * Gets the value of the scanFile property.
     * 
     * @return
     *     possible object is
     *     {@link ScanFileType }
     *     
     */
    public ScanFileType getScanFile() {
        return scanFile;
    }

    /**
     * Sets the value of the scanFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanFileType }
     *     
     */
    public void setScanFile(ScanFileType value) {
        this.scanFile = value;
    }

    /**
     * Gets the value of the npmfConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ImsPmConfigType.NPMFConfig }
     *     
     */
    public ImsPmConfigType.NPMFConfig getNPMFConfig() {
        return npmfConfig;
    }

    /**
     * Sets the value of the npmfConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImsPmConfigType.NPMFConfig }
     *     
     */
    public void setNPMFConfig(ImsPmConfigType.NPMFConfig value) {
        this.npmfConfig = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pmApplication">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="reportingRootDirectory">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="maxMonitorNr">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="500"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="measReaderNr">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="timeZone">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="utc"/>
     *                         &lt;enumeration value="local"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="maxPmdbMemSize">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
     *                         &lt;minInclusive value="4"/>
     *                         &lt;maxInclusive value="64"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="maxPmdbCpuLoad">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *                         &lt;minInclusive value="0.1"/>
     *                         &lt;maxInclusive value="100"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="maxAlarmPerMeasType">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
     *                         &lt;minInclusive value="3"/>
     *                         &lt;maxInclusive value="100"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="monitorGroup" type="{com:ericsson:ims:mim}monitorGroupType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pmApplication"
    })
    public static class NPMFConfig {

        @XmlElement(required = true)
        protected ImsPmConfigType.NPMFConfig.PmApplication pmApplication;

        /**
         * Gets the value of the pmApplication property.
         * 
         * @return
         *     possible object is
         *     {@link ImsPmConfigType.NPMFConfig.PmApplication }
         *     
         */
        public ImsPmConfigType.NPMFConfig.PmApplication getPmApplication() {
            return pmApplication;
        }

        /**
         * Sets the value of the pmApplication property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImsPmConfigType.NPMFConfig.PmApplication }
         *     
         */
        public void setPmApplication(ImsPmConfigType.NPMFConfig.PmApplication value) {
            this.pmApplication = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="reportingRootDirectory">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="maxMonitorNr">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="500"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="measReaderNr">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="timeZone">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="utc"/>
         *               &lt;enumeration value="local"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="maxPmdbMemSize">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
         *               &lt;minInclusive value="4"/>
         *               &lt;maxInclusive value="64"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="maxPmdbCpuLoad">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
         *               &lt;minInclusive value="0.1"/>
         *               &lt;maxInclusive value="100"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="maxAlarmPerMeasType">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
         *               &lt;minInclusive value="3"/>
         *               &lt;maxInclusive value="100"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="monitorGroup" type="{com:ericsson:ims:mim}monitorGroupType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reportingRootDirectory",
            "enable",
            "maxMonitorNr",
            "measReaderNr",
            "timeZone",
            "maxPmdbMemSize",
            "maxPmdbCpuLoad",
            "maxAlarmPerMeasType",
            "monitorGroup"
        })
        public static class PmApplication {

            @XmlElement(required = true)
            protected String reportingRootDirectory;
            @XmlElement(defaultValue = "true")
            protected boolean enable;
            @XmlElement(defaultValue = "300")
            protected long maxMonitorNr;
            @XmlElement(defaultValue = "3000")
            protected long measReaderNr;
            @XmlElement(required = true, defaultValue = "local")
            protected String timeZone;
            @XmlElement(defaultValue = "16")
            protected long maxPmdbMemSize;
            @XmlElement(defaultValue = "1")
            protected float maxPmdbCpuLoad;
            @XmlElement(defaultValue = "10")
            protected short maxAlarmPerMeasType;
            @XmlElement(required = true)
            protected List<MonitorGroupType> monitorGroup;

            /**
             * Gets the value of the reportingRootDirectory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReportingRootDirectory() {
                return reportingRootDirectory;
            }

            /**
             * Sets the value of the reportingRootDirectory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReportingRootDirectory(String value) {
                this.reportingRootDirectory = value;
            }

            /**
             * Gets the value of the enable property.
             * 
             */
            public boolean isEnable() {
                return enable;
            }

            /**
             * Sets the value of the enable property.
             * 
             */
            public void setEnable(boolean value) {
                this.enable = value;
            }

            /**
             * Gets the value of the maxMonitorNr property.
             * 
             */
            public long getMaxMonitorNr() {
                return maxMonitorNr;
            }

            /**
             * Sets the value of the maxMonitorNr property.
             * 
             */
            public void setMaxMonitorNr(long value) {
                this.maxMonitorNr = value;
            }

            /**
             * Gets the value of the measReaderNr property.
             * 
             */
            public long getMeasReaderNr() {
                return measReaderNr;
            }

            /**
             * Sets the value of the measReaderNr property.
             * 
             */
            public void setMeasReaderNr(long value) {
                this.measReaderNr = value;
            }

            /**
             * Gets the value of the timeZone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeZone() {
                return timeZone;
            }

            /**
             * Sets the value of the timeZone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeZone(String value) {
                this.timeZone = value;
            }

            /**
             * Gets the value of the maxPmdbMemSize property.
             * 
             */
            public long getMaxPmdbMemSize() {
                return maxPmdbMemSize;
            }

            /**
             * Sets the value of the maxPmdbMemSize property.
             * 
             */
            public void setMaxPmdbMemSize(long value) {
                this.maxPmdbMemSize = value;
            }

            /**
             * Gets the value of the maxPmdbCpuLoad property.
             * 
             */
            public float getMaxPmdbCpuLoad() {
                return maxPmdbCpuLoad;
            }

            /**
             * Sets the value of the maxPmdbCpuLoad property.
             * 
             */
            public void setMaxPmdbCpuLoad(float value) {
                this.maxPmdbCpuLoad = value;
            }

            /**
             * Gets the value of the maxAlarmPerMeasType property.
             * 
             */
            public short getMaxAlarmPerMeasType() {
                return maxAlarmPerMeasType;
            }

            /**
             * Sets the value of the maxAlarmPerMeasType property.
             * 
             */
            public void setMaxAlarmPerMeasType(short value) {
                this.maxAlarmPerMeasType = value;
            }

            /**
             * Gets the value of the monitorGroup property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the monitorGroup property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMonitorGroup().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MonitorGroupType }
             * 
             * 
             */
            public List<MonitorGroupType> getMonitorGroup() {
                if (monitorGroup == null) {
                    monitorGroup = new ArrayList<MonitorGroupType>();
                }
                return this.monitorGroup;
            }

        }

    }

}
