//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for measurementJobType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="measurementJobType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="priority">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="granularityPeriod">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="300"/>
 *               &lt;enumeration value="900"/>
 *               &lt;enumeration value="1800"/>
 *               &lt;enumeration value="3600"/>
 *               &lt;enumeration value="43200"/>
 *               &lt;enumeration value="86400"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="notifyMOEvents" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="reportingDirectory">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="notifyFileReady" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="reportingFormat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="XSD"/>
 *               &lt;enumeration value="DTD"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="measurementJobReader" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="64"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "measurementJobType", propOrder = {
    "name",
    "enabled",
    "priority",
    "granularityPeriod",
    "notifyMOEvents",
    "reportingDirectory",
    "notifyFileReady",
    "reportingFormat",
    "measurementJobReader"
})
public class MeasurementJobType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(defaultValue = "true")
    protected boolean enabled;
    @XmlElement(defaultValue = "64")
    protected int priority;
    @XmlElement(defaultValue = "300")
    protected int granularityPeriod;
    @XmlElement(defaultValue = "false")
    protected boolean notifyMOEvents;
    @XmlElement(required = true)
    protected String reportingDirectory;
    @XmlElement(defaultValue = "false")
    protected boolean notifyFileReady;
    @XmlElement(required = true, defaultValue = "XSD")
    protected String reportingFormat;
    @XmlElement(required = true)
    protected List<MeasurementJobType.MeasurementJobReader> measurementJobReader;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the granularityPeriod property.
     * 
     */
    public int getGranularityPeriod() {
        return granularityPeriod;
    }

    /**
     * Sets the value of the granularityPeriod property.
     * 
     */
    public void setGranularityPeriod(int value) {
        this.granularityPeriod = value;
    }

    /**
     * Gets the value of the notifyMOEvents property.
     * 
     */
    public boolean isNotifyMOEvents() {
        return notifyMOEvents;
    }

    /**
     * Sets the value of the notifyMOEvents property.
     * 
     */
    public void setNotifyMOEvents(boolean value) {
        this.notifyMOEvents = value;
    }

    /**
     * Gets the value of the reportingDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingDirectory() {
        return reportingDirectory;
    }

    /**
     * Sets the value of the reportingDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingDirectory(String value) {
        this.reportingDirectory = value;
    }

    /**
     * Gets the value of the notifyFileReady property.
     * 
     */
    public boolean isNotifyFileReady() {
        return notifyFileReady;
    }

    /**
     * Sets the value of the notifyFileReady property.
     * 
     */
    public void setNotifyFileReady(boolean value) {
        this.notifyFileReady = value;
    }

    /**
     * Gets the value of the reportingFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingFormat() {
        return reportingFormat;
    }

    /**
     * Sets the value of the reportingFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingFormat(String value) {
        this.reportingFormat = value;
    }

    /**
     * Gets the value of the measurementJobReader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurementJobReader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurementJobReader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasurementJobType.MeasurementJobReader }
     * 
     * 
     */
    public List<MeasurementJobType.MeasurementJobReader> getMeasurementJobReader() {
        if (measurementJobReader == null) {
            measurementJobReader = new ArrayList<MeasurementJobType.MeasurementJobReader>();
        }
        return this.measurementJobReader;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="64"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "enabled"
    })
    public static class MeasurementJobReader {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(defaultValue = "true")
        protected boolean enabled;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the enabled property.
         * 
         */
        public boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         */
        public void setEnabled(boolean value) {
            this.enabled = value;
        }

    }

}
