//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for pmMimMetadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pmMimMetadataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nodeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="node_major_version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="node_minor_version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="pmMimVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imsMimVersionDoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pmMimMetadataType", propOrder = {
    "nodeType",
    "nodeMajorVersion",
    "nodeMinorVersion",
    "timestamp",
    "pmMimVersion",
    "imsMimVersionDoc"
})
public class PmMimMetadataType {

    @XmlElement(required = true)
    protected String nodeType;
    @XmlElement(name = "node_major_version")
    protected String nodeMajorVersion;
    @XmlElement(name = "node_minor_version")
    protected String nodeMinorVersion;
    @XmlElement(required = true)
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected String pmMimVersion;
    @XmlElement(required = true)
    protected String imsMimVersionDoc;

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeType(String value) {
        this.nodeType = value;
    }

    /**
     * Gets the value of the nodeMajorVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeMajorVersion() {
        return nodeMajorVersion;
    }

    /**
     * Sets the value of the nodeMajorVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeMajorVersion(String value) {
        this.nodeMajorVersion = value;
    }

    /**
     * Gets the value of the nodeMinorVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeMinorVersion() {
        return nodeMinorVersion;
    }

    /**
     * Sets the value of the nodeMinorVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeMinorVersion(String value) {
        this.nodeMinorVersion = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the pmMimVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmMimVersion() {
        return pmMimVersion;
    }

    /**
     * Sets the value of the pmMimVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmMimVersion(String value) {
        this.pmMimVersion = value;
    }

    /**
     * Gets the value of the imsMimVersionDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImsMimVersionDoc() {
        return imsMimVersionDoc;
    }

    /**
     * Sets the value of the imsMimVersionDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImsMimVersionDoc(String value) {
        this.imsMimVersionDoc = value;
    }

}
