//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scanFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scanFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="simplescanperiod" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="intrascanperiod" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="granularityperiod" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="applicationpool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loggingenabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="logfiledirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tracelevel" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scanFileType", propOrder = {
    "identity",
    "simplescanperiod",
    "intrascanperiod",
    "granularityperiod",
    "applicationpool",
    "loggingenabled",
    "logfiledirectory",
    "tracelevel"
})
public class ScanFileType {

    @XmlElement(required = true)
    protected String identity;
    @XmlSchemaType(name = "unsignedInt")
    protected long simplescanperiod;
    @XmlSchemaType(name = "unsignedInt")
    protected long intrascanperiod;
    @XmlSchemaType(name = "unsignedInt")
    protected long granularityperiod;
    @XmlElement(required = true)
    protected String applicationpool;
    protected boolean loggingenabled;
    @XmlElement(required = true)
    protected String logfiledirectory;
    @XmlSchemaType(name = "unsignedInt")
    protected long tracelevel;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the simplescanperiod property.
     * 
     */
    public long getSimplescanperiod() {
        return simplescanperiod;
    }

    /**
     * Sets the value of the simplescanperiod property.
     * 
     */
    public void setSimplescanperiod(long value) {
        this.simplescanperiod = value;
    }

    /**
     * Gets the value of the intrascanperiod property.
     * 
     */
    public long getIntrascanperiod() {
        return intrascanperiod;
    }

    /**
     * Sets the value of the intrascanperiod property.
     * 
     */
    public void setIntrascanperiod(long value) {
        this.intrascanperiod = value;
    }

    /**
     * Gets the value of the granularityperiod property.
     * 
     */
    public long getGranularityperiod() {
        return granularityperiod;
    }

    /**
     * Sets the value of the granularityperiod property.
     * 
     */
    public void setGranularityperiod(long value) {
        this.granularityperiod = value;
    }

    /**
     * Gets the value of the applicationpool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationpool() {
        return applicationpool;
    }

    /**
     * Sets the value of the applicationpool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationpool(String value) {
        this.applicationpool = value;
    }

    /**
     * Gets the value of the loggingenabled property.
     * 
     */
    public boolean isLoggingenabled() {
        return loggingenabled;
    }

    /**
     * Sets the value of the loggingenabled property.
     * 
     */
    public void setLoggingenabled(boolean value) {
        this.loggingenabled = value;
    }

    /**
     * Gets the value of the logfiledirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogfiledirectory() {
        return logfiledirectory;
    }

    /**
     * Sets the value of the logfiledirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogfiledirectory(String value) {
        this.logfiledirectory = value;
    }

    /**
     * Gets the value of the tracelevel property.
     * 
     */
    public long getTracelevel() {
        return tracelevel;
    }

    /**
     * Sets the value of the tracelevel property.
     * 
     */
    public void setTracelevel(long value) {
        this.tracelevel = value;
    }

}
