//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:36 PM IST 
//


package com.ericsson.ims.mim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThresholdMonitorReaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThresholdMonitorReaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="criticalLevel" type="{com:ericsson:ims:mim}ArmDisarmlevelType" minOccurs="0"/>
 *         &lt;element name="majorLevel" type="{com:ericsson:ims:mim}ArmDisarmlevelType" minOccurs="0"/>
 *         &lt;element name="minorLevel" type="{com:ericsson:ims:mim}ArmDisarmlevelType" minOccurs="0"/>
 *         &lt;element name="warningLevel" type="{com:ericsson:ims:mim}ArmDisarmlevelType" minOccurs="0"/>
 *         &lt;element name="faultId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="alarmDirection">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Up"/>
 *               &lt;enumeration value="Down"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Reached"/>
 *               &lt;enumeration value="Crossed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Communication"/>
 *               &lt;enumeration value="QualityOfService"/>
 *               &lt;enumeration value="ProcessingError"/>
 *               &lt;enumeration value="Equipment"/>
 *               &lt;enumeration value="Environmental"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="specificProblem">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="probableCause" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="alarmObjectClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="additionalInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThresholdMonitorReaderType", propOrder = {
    "name",
    "enabled",
    "criticalLevel",
    "majorLevel",
    "minorLevel",
    "warningLevel",
    "faultId",
    "alarmDirection",
    "mode",
    "type",
    "specificProblem",
    "probableCause",
    "alarmObjectClass",
    "additionalInfo"
})
public class ThresholdMonitorReaderType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(defaultValue = "true")
    protected boolean enabled;
    protected ArmDisarmlevelType criticalLevel;
    protected ArmDisarmlevelType majorLevel;
    protected ArmDisarmlevelType minorLevel;
    protected ArmDisarmlevelType warningLevel;
    protected int faultId;
    @XmlElement(required = true)
    protected String alarmDirection;
    @XmlElement(required = true)
    protected String mode;
    @XmlElement(required = true, defaultValue = "QualityOfService")
    protected String type;
    @XmlElement(required = true, defaultValue = "Performance Management, Threshold Crossed or Reached")
    protected String specificProblem;
    @XmlElement(defaultValue = "351")
    protected int probableCause;
    @XmlElement(required = true)
    protected String alarmObjectClass;
    @XmlElement(required = true)
    protected String additionalInfo;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the criticalLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public ArmDisarmlevelType getCriticalLevel() {
        return criticalLevel;
    }

    /**
     * Sets the value of the criticalLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public void setCriticalLevel(ArmDisarmlevelType value) {
        this.criticalLevel = value;
    }

    /**
     * Gets the value of the majorLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public ArmDisarmlevelType getMajorLevel() {
        return majorLevel;
    }

    /**
     * Sets the value of the majorLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public void setMajorLevel(ArmDisarmlevelType value) {
        this.majorLevel = value;
    }

    /**
     * Gets the value of the minorLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public ArmDisarmlevelType getMinorLevel() {
        return minorLevel;
    }

    /**
     * Sets the value of the minorLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public void setMinorLevel(ArmDisarmlevelType value) {
        this.minorLevel = value;
    }

    /**
     * Gets the value of the warningLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public ArmDisarmlevelType getWarningLevel() {
        return warningLevel;
    }

    /**
     * Sets the value of the warningLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArmDisarmlevelType }
     *     
     */
    public void setWarningLevel(ArmDisarmlevelType value) {
        this.warningLevel = value;
    }

    /**
     * Gets the value of the faultId property.
     * 
     */
    public int getFaultId() {
        return faultId;
    }

    /**
     * Sets the value of the faultId property.
     * 
     */
    public void setFaultId(int value) {
        this.faultId = value;
    }

    /**
     * Gets the value of the alarmDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmDirection() {
        return alarmDirection;
    }

    /**
     * Sets the value of the alarmDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmDirection(String value) {
        this.alarmDirection = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the specificProblem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificProblem() {
        return specificProblem;
    }

    /**
     * Sets the value of the specificProblem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificProblem(String value) {
        this.specificProblem = value;
    }

    /**
     * Gets the value of the probableCause property.
     * 
     */
    public int getProbableCause() {
        return probableCause;
    }

    /**
     * Sets the value of the probableCause property.
     * 
     */
    public void setProbableCause(int value) {
        this.probableCause = value;
    }

    /**
     * Gets the value of the alarmObjectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmObjectClass() {
        return alarmObjectClass;
    }

    /**
     * Sets the value of the alarmObjectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmObjectClass(String value) {
        this.alarmObjectClass = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

}
