//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:53 PM IST 
//


package com.ericsson.eniq.afj.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for counterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="counterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="measurementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectionMethod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="CC"/>
 *                         &lt;enumeration value="SI"/>
 *                         &lt;enumeration value="GAUGE"/>
 *                         &lt;enumeration value="DER"/>
 *                         &lt;enumeration value="IDENTITY"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="subtype">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="MIN"/>
 *                         &lt;enumeration value="MAX"/>
 *                         &lt;enumeration value="LAST_UPDATE"/>
 *                         &lt;enumeration value="RAW"/>
 *                         &lt;enumeration value="MEAN"/>
 *                         &lt;enumeration value="SUM"/>
 *                         &lt;enumeration value=""/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="measurementResult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="outputUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="resultType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="decimal"/>
 *                         &lt;enumeration value="integer"/>
 *                         &lt;enumeration value="float"/>
 *                         &lt;enumeration value="byte"/>
 *                         &lt;enumeration value="int"/>
 *                         &lt;enumeration value="smallInt"/>
 *                         &lt;enumeration value="unsignedInt"/>
 *                         &lt;enumeration value="long"/>
 *                         &lt;enumeration value="double"/>
 *                         &lt;enumeration value="dateTime"/>
 *                         &lt;enumeration value="date"/>
 *                         &lt;enumeration value="time"/>
 *                         &lt;enumeration value="boolean"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="resultType_freeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="current"/>
 *               &lt;enumeration value="obsolete"/>
 *               &lt;enumeration value="deprecated"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="measurementType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "counterType", propOrder = {
    "measurementName",
    "description",
    "collectionMethod",
    "measurementResult",
    "status"
})
public class CounterType {

    @XmlElement(required = true)
    protected String measurementName;
    @XmlElement(required = true, defaultValue = "\"\"")
    protected String description;
    @XmlElement(required = true)
    protected CounterType.CollectionMethod collectionMethod;
    @XmlElement(required = true)
    protected CounterType.MeasurementResult measurementResult;
    @XmlElement(required = true, defaultValue = "current")
    protected String status;
    @XmlAttribute(required = true)
    protected String measurementType;

    /**
     * Gets the value of the measurementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementName() {
        return measurementName;
    }

    /**
     * Sets the value of the measurementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementName(String value) {
        this.measurementName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the collectionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CounterType.CollectionMethod }
     *     
     */
    public CounterType.CollectionMethod getCollectionMethod() {
        return collectionMethod;
    }

    /**
     * Sets the value of the collectionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterType.CollectionMethod }
     *     
     */
    public void setCollectionMethod(CounterType.CollectionMethod value) {
        this.collectionMethod = value;
    }

    /**
     * Gets the value of the measurementResult property.
     * 
     * @return
     *     possible object is
     *     {@link CounterType.MeasurementResult }
     *     
     */
    public CounterType.MeasurementResult getMeasurementResult() {
        return measurementResult;
    }

    /**
     * Sets the value of the measurementResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterType.MeasurementResult }
     *     
     */
    public void setMeasurementResult(CounterType.MeasurementResult value) {
        this.measurementResult = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the measurementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementType() {
        return measurementType;
    }

    /**
     * Sets the value of the measurementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementType(String value) {
        this.measurementType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CC"/>
     *               &lt;enumeration value="SI"/>
     *               &lt;enumeration value="GAUGE"/>
     *               &lt;enumeration value="DER"/>
     *               &lt;enumeration value="IDENTITY"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="subtype">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MIN"/>
     *               &lt;enumeration value="MAX"/>
     *               &lt;enumeration value="LAST_UPDATE"/>
     *               &lt;enumeration value="RAW"/>
     *               &lt;enumeration value="MEAN"/>
     *               &lt;enumeration value="SUM"/>
     *               &lt;enumeration value=""/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "subtype"
    })
    public static class CollectionMethod {

        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String subtype;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the subtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubtype() {
            return subtype;
        }

        /**
         * Sets the value of the subtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubtype(String value) {
            this.subtype = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="outputUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="resultType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="decimal"/>
     *               &lt;enumeration value="integer"/>
     *               &lt;enumeration value="float"/>
     *               &lt;enumeration value="byte"/>
     *               &lt;enumeration value="int"/>
     *               &lt;enumeration value="smallInt"/>
     *               &lt;enumeration value="unsignedInt"/>
     *               &lt;enumeration value="long"/>
     *               &lt;enumeration value="double"/>
     *               &lt;enumeration value="dateTime"/>
     *               &lt;enumeration value="date"/>
     *               &lt;enumeration value="time"/>
     *               &lt;enumeration value="boolean"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="resultType_freeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outputUnit",
        "resultType",
        "resultTypeFreeText"
    })
    public static class MeasurementResult {

        @XmlElement(required = true)
        protected String outputUnit;
        @XmlElement(required = true)
        protected String resultType;
        @XmlElement(name = "resultType_freeText")
        protected String resultTypeFreeText;

        /**
         * Gets the value of the outputUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputUnit() {
            return outputUnit;
        }

        /**
         * Sets the value of the outputUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputUnit(String value) {
            this.outputUnit = value;
        }

        /**
         * Gets the value of the resultType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultType() {
            return resultType;
        }

        /**
         * Sets the value of the resultType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultType(String value) {
            this.resultType = value;
        }

        /**
         * Gets the value of the resultTypeFreeText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultTypeFreeText() {
            return resultTypeFreeText;
        }

        /**
         * Sets the value of the resultTypeFreeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultTypeFreeText(String value) {
            this.resultTypeFreeText = value;
        }

    }

}
