//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.10 at 03:55:53 PM IST 
//


package com.ericsson.eniq.afj.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.eniq.afj.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.eniq.afj.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CounterType.MeasurementResult }
     * 
     */
    public CounterType.MeasurementResult createCounterTypeMeasurementResult() {
        return new CounterType.MeasurementResult();
    }

    /**
     * Create an instance of {@link MocType }
     * 
     */
    public MocType createMocType() {
        return new MocType();
    }

    /**
     * Create an instance of {@link CapabilitiesType }
     * 
     */
    public CapabilitiesType createCapabilitiesType() {
        return new CapabilitiesType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link PM.PmMimMetadata }
     * 
     */
    public PM.PmMimMetadata createPMPmMimMetadata() {
        return new PM.PmMimMetadata();
    }

    /**
     * Create an instance of {@link PM }
     * 
     */
    public PM createPM() {
        return new PM();
    }

    /**
     * Create an instance of {@link CounterType }
     * 
     */
    public CounterType createCounterType() {
        return new CounterType();
    }

    /**
     * Create an instance of {@link CounterType.CollectionMethod }
     * 
     */
    public CounterType.CollectionMethod createCounterTypeCollectionMethod() {
        return new CounterType.CollectionMethod();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link CapabilitiesType.CounterCapabilities }
     * 
     */
    public CapabilitiesType.CounterCapabilities createCapabilitiesTypeCounterCapabilities() {
        return new CapabilitiesType.CounterCapabilities();
    }

}
