insert into Versioning (versionid, description, status, techpack_name, techpack_version, techpack_type, product_number) values ('DC_Z_ALARM:b(build)','PM Alarm b(build)',1,'DC_Z_ALARM','R20A_b(build)','EVENT','COA 252 125');


insert into MeasurementTypeClass (typeclassid, versionid, description) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_PM_Alarm','DC_Z_ALARM:b(build)','PM Alarm');
insert into MeasurementType (typeid, typeclassid, typename, vendorid, foldername, description, versionid, objectid, objectname, joinable) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','DC_Z_ALARM:b(build):DC_Z_ALARM_PM_Alarm','DC_Z_ALARM_INFO','DC_Z_ALARM','DC_Z_ALARM_INFO','PM Alarm Events','DC_Z_ALARM:b(build)','DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','DC_Z_ALARM_INFO','');
insert into MeasurementKey (typeid, dataname, description, iselement, uniquekey) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','NotificationIdentifier','Notification identifiers must be chosen to be unique across all notifications of a particular managed object throughout the time that correlation is significant.',0,0);
insert into MeasurementKey (typeid, dataname, description, iselement, uniquekey) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ObjectOfReference','Object of reference',0,1);
insert into MeasurementKey (typeid, dataname, description, iselement, uniquekey) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ManagedObjectInstance','Managed Object Instance',1,1);
insert into MeasurementKey (typeid, dataname, description, iselement, uniquekey) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ReportTitle','Title of the report',0,1);
insert into MeasurementKey (typeid, dataname, description, iselement, uniquekey) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','OssName','Name of the OSS',0,1);
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','InvokeIdentifier','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ModeId','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','EventDate','Event date','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','EventHour','Event hour','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','EventMinute','Event minute','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ETText','Event type in text format.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','CurrentDate','The date when notification received.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','CurrentHour','The hour when notification received.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','CurrentMinute','The minute when notification received.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','PCText','The text, used to represent the probable cause of alarm.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','SPText','One of the following:  Static threshold, Trend derivative, Number of hits, Number of continuous occurrences.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','PerceivedSeverity','Integer that indicates how the capability of the Managed Object has been affected. 0 - Indeterminate 1 - Critical 2 - Major 3 - Minor 4 - Warning 5 - Cleared','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','PerceivedSeverityText','Perceived severity in text format. One of following: Indeterminate, Critical, Major, Minor, Warning, Cleared.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','BackedUpStatus','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','BackupObject','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','TrendIndication','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','CorrelatedNotifications','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','StateChangeDefinition','N/A','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ProposedRepairActions','The integer, representing the proposed repair actions.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','AdditionalText','Free form text','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','AdditionalInformation','This parameter, when present, allows the inclusion of a set of additional information in the event report. It is a series of data structures each of which contains three items of information: an identifier, a significance indicator, and the problem information.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','MonitoredAttributeValues','Value of the monitored attribute. Example:  11,644','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','MonitoredAttributes','Information on the monitored attributes. Example:  pmDlTrafficVolumePsStr128Ps8','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','SpecificProblems','This parameter, when present, identifies further refinements to the Probable cause of the alarm. This parameter qualifies the chosen Probable cause and may be used by the managed object class definer to specify a set of identifiers for use in managed object classes. Example: 1002000000','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ThresholdInformation','Free text describing the threshold. Example: > 11600.','NONE','NONE','');
insert into MeasurementCounter (typeid, dataname, description, timeaggregation, groupaggregation, countaggregation) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','ManagedObjectClass','Class of managed object','NONE','NONE','');
insert into MeasurementTable (mtableid, typeid, tablelevel, basetablename, partitionplan) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW','DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','RAW','DC_Z_ALARM_INFO_RAW','small_raw');
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',1,'NotificationIdentifier','int',0,0,255,1,'HG','Notification identifiers must be chosen to be unique across all notifications of a particular managed object throughout the time that correlation is significant.','NotificationIdentifier','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',2,'ObjectOfReference','varchar',255,0,255,1,'HG','Object of reference','ObjectOfReference','b(build)',1,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',3,'ManagedObjectInstance','varchar',100,0,255,1,'HG','Managed Object Instance','ManagedObjectInstance','b(build)',1,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',4,'ReportTitle','varchar',100,0,255,1,'HG','Title of the report','ReportTitle','b(build)',1,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',5,'OssName','varchar',255,0,255,1,'HG','Name of the OSS','OssName','b(build)',1,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',51,'DATE_ID','date',0,0,255,1,'LF','','DATE_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',52,'YEAR_ID','smallint',0,0,20,1,'LF','','YEAR_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',53,'MONTH_ID','tinyint',0,0,12,1,'LF','','MONTH_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',54,'DAY_ID','tinyint',0,0,31,1,'LF','','DAY_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',55,'HOUR_ID','tinyint',0,0,24,1,'LF','','HOUR_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',56,'DATETIME_ID','datetime',0,0,255,1,'HG','','DATETIME_ID','b(build)',1,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',57,'MIN_ID','tinyint',0,0,60,1,'LF','','MIN_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',58,'TIMELEVEL','varchar',10,0,10,1,'LF','','TIMELEVEL','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',59,'SESSION_ID','unsigned int',0,0,255,1,'','','SESSION_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',60,'BATCH_ID','smallint',0,0,255,1,'','','BATCH_ID','b(build)',0,0);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',61,'PERIOD_DURATION','unsigned int',0,0,10,1,'','','PERIOD_DURATION','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',62,'ROWSTATUS','varchar',16,0,10,1,'','','ROWSTATUS','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',63,'DC_RELEASE','varchar',16,0,2,1,'LF','','DC_RELEASE','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',64,'DC_SOURCE','varchar',16,0,2,1,'LF','','DC_SOURCE','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',65,'DC_TIMEZONE','varchar',16,0,2,1,'LF','','DC_TIMEZONE','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',66,'DC_SUSPECTFLAG','int',0,0,2,1,'LF','','DC_SUSPECTFLAG','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',67,'UTC_DATETIME_ID','datetime',0,0,255,1,'HG','','UTC_DATETIME_ID','b(build)',1,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',101,'InvokeIdentifier','varchar',100,0,255,1,'','N/A','InvokeIdentifier','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',102,'ModeId','varchar',100,0,255,1,'','N/A','ModeId','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',103,'EventDate','datetime',0,0,255,1,'','Event date','EventDate','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',104,'EventHour','int',0,0,255,1,'','Event hour','EventHour','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',105,'EventMinute','int',0,0,255,1,'','Event minute','EventMinute','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',106,'ETText','varchar',30,0,255,1,'','Event type in text format.','ETText','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',107,'CurrentDate','date',0,0,255,1,'','The date when notification received.','CurrentDate','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',108,'CurrentHour','int',0,0,255,1,'','The hour when notification received.','CurrentHour','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',109,'CurrentMinute','int',0,0,255,1,'','The minute when notification received.','CurrentMinute','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',110,'PCText','varchar',200,0,255,1,'','The text, used to represent the probable cause of alarm.','PCText','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',111,'SPText','varchar',100,0,255,1,'','One of the following:  Static threshold, Trend derivative, Number of hits, Number of continuous occurrences.','SPText','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',112,'PerceivedSeverity','int',0,0,255,1,'','Integer that indicates how the capability of the Managed Object has been affected. 0 - Indeterminate 1 - Critical 2 - Major 3 - Minor 4 - Warning 5 - Cleared','PerceivedSeverity','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',113,'PerceivedSeverityText','varchar',100,0,255,1,'','Perceived severity in text format. One of following: Indeterminate, Critical, Major, Minor, Warning, Cleared.','PerceivedSeverityText','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',114,'BackedUpStatus','varchar',3,0,255,1,'','N/A','BackedUpStatus','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',115,'BackupObject','varchar',100,0,255,1,'','N/A','BackupObject','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',116,'TrendIndication','varchar',30,0,255,1,'','N/A','TrendIndication','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',117,'CorrelatedNotifications','varchar',255,0,255,1,'','N/A','CorrelatedNotifications','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',118,'StateChangeDefinition','varchar',50,0,255,1,'','N/A','StateChangeDefinition','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',119,'ProposedRepairActions','varchar',100,0,255,1,'','The integer, representing the proposed repair actions.','ProposedRepairActions','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',120,'AdditionalText','varchar',1000,0,255,1,'','Free form text','AdditionalText','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',121,'AdditionalInformation','varchar',1000,0,255,1,'','This parameter, when present, allows the inclusion of a set of additional information in the event report. It is a series of data structures each of which contains three items of information: an identifier, a significance indicator, and the problem information.','AdditionalInformation','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',122,'MonitoredAttributeValues','varchar',255,0,255,1,'','Value of the monitored attribute. Example:  11,644','MonitoredAttributeValues','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',123,'MonitoredAttributes','varchar',255,0,255,1,'','Information on the monitored attributes. Example:  pmDlTrafficVolumePsStr128Ps8','MonitoredAttributes','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',124,'SpecificProblems','varchar',255,0,255,1,'','This parameter, when present, identifies further refinements to the Probable cause of the alarm. This parameter qualifies the chosen Probable cause and may be used by the managed object class definer to specify a set of identifiers for use in managed object classes. Example: 1002000000','SpecificProblems','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',125,'ThresholdInformation','varchar',255,0,255,1,'','Free text describing the threshold. Example: > 11600.','ThresholdInformation','b(build)',0,1);
insert into MeasurementColumn (mtableid, colnumber, dataname, datatype, datasize, datascale, uniquevalue, nullable, indexes, description, dataid, releaseid, uniquekey, includesql) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:RAW',126,'ManagedObjectClass','varchar',100,0,255,1,'','Class of managed object','ManagedObjectClass','b(build)',0,1);



insert into DataFormat ( dataformatid, typeid, versionid, objecttype, foldername, dataformattype) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DC_Z_ALARM:b(build):DC_Z_ALARM_INFO','DC_Z_ALARM:b(build)','Measurement','DC_Z_ALARM_INFO','ALARM');

insert into DefaultTags (tagid, dataformatid, description) values ('alarm','DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','Default tags for DC_Z_ALARM_INFO in DC_Z_ALARM:b(build) with format ALARM.');

insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','NotificationIdentifier',1,'NotificationIdentifier','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ObjectOfReference',125,'ObjectOfReference','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ManagedObjectInstance',3,'ManagedObjectInstance','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ReportTitle',4,'ReportTitle','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','OssName',124,'OssName','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DATE_ID',51,'DATE_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','YEAR_ID',52,'YEAR_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','MONTH_ID',53,'MONTH_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DAY_ID',54,'DAY_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','HOUR_ID',55,'HOUR_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DATETIME_ID',56,'DATETIME_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','MIN_ID',57,'MIN_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','TIMELEVEL',58,'TIMELEVEL','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','SESSION_ID',59,'SESSION_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','BATCH_ID',60,'BATCH_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','PERIOD_DURATION',61,'PERIOD_DURATION','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ROWSTATUS',62,'ROWSTATUS','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DC_RELEASE',63,'DC_RELEASE','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DC_SOURCE',64,'DC_SOURCE','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DC_TIMEZONE',65,'DC_TIMEZONE','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DC_SUSPECTFLAG',66,'DC_SUSPECTFLAG','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','UTC_DATETIME_ID',67,'UTC_DATETIME_ID','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','InvokeIdentifier',101,'InvokeIdentifier','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ModeId',102,'ModeId','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','EventDate',103,'EventDate','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','EventHour',104,'EventHour','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','EventMinute',105,'EventMinute','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ETText',106,'ETText','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','CurrentDate',107,'CurrentDate','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','CurrentHour',108,'CurrentHour','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','CurrentMinute',109,'CurrentMinute','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','PCText',110,'PCText','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','SPText',111,'SPText','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','PerceivedSeverity',112,'PerceivedSeverity','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','PerceivedSeverityText',113,'PerceivedSeverityText','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','BackedUpStatus',114,'BackedUpStatus','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','BackupObject',115,'BackupObject','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','TrendIndication',116,'TrendIndication','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','CorrelatedNotifications',117,'CorrelatedNotifications','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','StateChangeDefinition',118,'StateChangeDefinition','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ProposedRepairActions',119,'ProposedRepairActions','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','AdditionalText',120,'AdditionalText','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','AdditionalInformation',121,'AdditionalInformation','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','MonitoredAttributeValues',122,'MonitoredAttributeValues','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','MonitoredAttributes',123,'MonitoredAttributes','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','SpecificProblems',126,'SpecificProblems','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ThresholdInformation',127,'ThresholdInformation','');
insert into DataItem (dataformatid, dataname, colnumber, dataid, process_instruction) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','ManagedObjectClass',2,'ManagedObjectClass','');





insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','create view SELECT_Z_ALARM_AGGLEVEL',1,'dwh','IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_Z_ALARM_AGGLEVEL'') > 0 
DROP VIEW SELECT_Z_ALARM_AGGLEVEL
BEGIN 
create view
  SELECT_Z_ALARM_AGGLEVEL(FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,
  TIMELEVEL,TIMELEVELBH,DAYS)
  as select FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,
  TIMELEVEL,TIMELEVELBH,DAYS from dc.SELECT_AGGLEVEL_TABLE
  WHERE TIMELEVELBH = ''DAYBH''
commit
grant select on SELECT_Z_ALARM_AGGLEVEL to dcbo
END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_5min',2,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_1'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_1'',''To Be Alarmed for AlarmInterface_5min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_10min',3,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_2'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_2'',''To Be Alarmed for AlarmInterface_10min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_15min',4,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_3'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_3'',''To Be Alarmed for AlarmInterface_15min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_30min',5,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_4'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_4'',''To Be Alarmed for AlarmInterface_30min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_60min',6,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_5'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_5'',''To Be Alarmed for AlarmInterface_60min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_6h',7,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_6'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_6'',''To Be Alarmed for AlarmInterface_6h'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_12h',8,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_7'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_7'',''To Be Alarmed for AlarmInterface_12h'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for To Be Alarmed for AlarmInterface_24h',9,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''TBA_8'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''TBA_8'',''To Be Alarmed for AlarmInterface_24h'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_5min',10,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_1'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_1'',''Processed By Alarm for AlarmInterface_5min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_10min',11,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_2'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_2'',''Processed By Alarm for AlarmInterface_10min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_15min',12,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_3'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_3'',''Processed By Alarm for AlarmInterface_15min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_30min',13,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_4'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_4'',''Processed By Alarm for AlarmInterface_30min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_60min',14,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_5'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_5'',''Processed By Alarm for AlarmInterface_60min'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_6h',15,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_6'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_6'',''Processed By Alarm for AlarmInterface_6h'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_12h',16,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_7'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_7'',''Processed By Alarm for AlarmInterface_12h'') END');
insert into ExternalStatement (versionid,statementname, executionorder, dbconnection, statement) values ('DC_Z_ALARM:b(build)','DIM_ROWSTATUS for Processed By Alarm for AlarmInterface_24h',17,'dwh','IF (SELECT count(*) FROM dc.DIM_ROWSTATUS WHERE ROWSTATUS=''PBA_8'') = 0 BEGIN insert into dc.DIM_ROWSTATUS (ROWSTATUS, DESCRIPTION) values (''PBA_8'',''Processed By Alarm for AlarmInterface_24h'') END');

insert into Transformer (transformerid, versionid) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM','DC_Z_ALARM:b(build)');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',1,'defaulttimehandler','EventTime','','oldformat=yyyy-MM-dd HH:mm');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',2,'dateformat','EventTime','EventDate','oldformat=yyyy-MM-dd HH:mm
newformat=yyyy-MM-dd');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',3,'dateformat','EventTime','EventHour','oldformat=yyyy-MM-dd HH:mm
newformat=HH');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',4,'dateformat','EventTime','EventMinute','oldformat=yyyy-MM-dd HH:mm
newformat=mm');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',5,'dateformat','CurrentTime','CurrentDate','oldformat=yyyy-MM-dd HH:mm:ss
newformat=yyyy-MM-dd');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',6,'dateformat','CurrentTime','CurrentHour','oldformat=yyyy-MM-dd HH:mm:ss
newformat=HH');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',7,'dateformat','CurrentTime','CurrentMinute','oldformat=yyyy-MM-dd HH:mm:ss
newformat=mm');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',8,'alarm','empty','empty','filenamePattern=alarm_$.xx
format=yyyy-MM-dd_HH:mm:ss:SSS');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',9,'condition','DC_TIMEZONE','DC_TIMEZONE','factor=TIMEZONE
result1field=JVM_TIMEZONE
result2field=DC_TIMEZONE');
insert into Transformation (transformerid, orderno, type, source, target, config) values ('DC_Z_ALARM:b(build):DC_Z_ALARM_INFO:ALARM',10,'DateFormat','DATETIME_ID','UTC_DATETIME_ID','oldformat=yyyy-MM-dd HH:mm
oldtimezone=+0000
newformat=yyyy-MM-dd HH:mm:ss
newtimezonefield=DC_TIMEZONE');

