--/***************************
--  META_DATABASES
--/***************************
create table META_DATABASES (
    USERNAME varchar(80) not null, 
    VERSION_NUMBER varchar(82) not null,
    TYPE_NAME varchar(115) not null, 
    CONNECTION_ID numeric(81) not null,
    CONNECTION_NAME varchar(80) not null,  
    CONNECTION_STRING varchar(200) not null,
    PASSWORD varchar(80), 
    DESCRIPTION varchar(32000), 
    DRIVER_NAME varchar(100) not null,
    DB_LINK_NAME varchar(128)
);

    
--/***************************
--  META_COLLECTION_SETS
--/***************************
create table META_COLLECTION_SETS (
	COLLECTION_SET_ID numeric(81) not null,
	COLLECTION_SET_NAME varchar(128) not null,
	DESCRIPTION varchar(32000),
	VERSION_NUMBER varchar(82) not null,
	ENABLED_FLAG varchar(10),
	TYPE varchar(82) 
);

alter table META_DATABASES
    add primary key (VERSION_NUMBER, CONNECTION_ID);

alter table META_COLLECTION_SETS
	add primary key (COLLECTION_SET_ID, VERSION_NUMBER);

--/***************************
--  Meta_schedulings
--/***************************
CREATE TABLE Meta_schedulings (
	VERSION_NUMBER VARCHAR(81),
	ID BIGINT,
	EXECUTION_TYPE VARCHAR(81),
	OS_COMMAND VARCHAR(81),
	SCHEDULING_MONTH BIGINT,
	SCHEDULING_DAY BIGINT,
	SCHEDULING_HOUR BIGINT,
	SCHEDULING_MIN BIGINT,
	COLLECTION_SET_ID BIGINT,
	COLLECTION_ID BIGINT,
	MON_FLAG VARCHAR(81),
	TUE_FLAG VARCHAR(81),
	WED_FLAG VARCHAR(81),
	THU_FLAG VARCHAR(81),
	FRI_FLAG VARCHAR(81),
	SAT_FLAG VARCHAR(81),
	SUN_FLAG VARCHAR(81),
	STATUS VARCHAR(81),
	LAST_EXECUTION_TIME TIMESTAMP,
	INTERVAL_HOUR BIGINT,
	INTERVAL_MIN BIGINT,
	NAME VARCHAR(81),
	HOLD_FLAG VARCHAR(81),
	PRIORITY BIGINT,
	SCHEDULING_YEAR BIGINT,
	TRIGGER_COMMAND VARCHAR(81),
	LAST_EXEC_TIME_MS BIGINT
);

--/***************************
--  Meta_collections
--/***************************
CREATE TABLE META_COLLECTIONS (
	COLLECTION_ID BIGINT,
	COLLECTION_NAME VARCHAR(81),
	COLLECTION VARCHAR(81),
	MAIL_ERROR_ADDR VARCHAR(81),
	MAIL_FAIL_ADDR VARCHAR(81),
	MAIL_BUG_ADDR VARCHAR(81),
	MAX_ERRORS BIGINT,
	MAX_FK_ERRORS BIGINT,
	MAX_COL_LIMIT_ERRORS BIGINT,
	CHECK_FK_ERROR_FLAG VARCHAR(81),
	CHECK_COL_LIMITS_FLAG VARCHAR(81),
	LAST_TRANSFER_DATE TIMESTAMP,
	VERSION_NUMBER VARCHAR(81),
	COLLECTION_SET_ID BIGINT,
	USE_BATCH_ID VARCHAR(81),
	PRIORITY BIGINT,
	QUEUE_TIME_LIMIT BIGINT,
	ENABLED_FLAG VARCHAR(81),
	SETTYPE VARCHAR(81),
	FOLDABLE_FLAG VARCHAR(81),
	MEASTYPE VARCHAR(81),
	HOLD_FLAG VARCHAR(81),
	SCHEDULING_INFO VARCHAR(81)
);

--/***************************
--  Meta_transfer_actions
--/***************************
CREATE TABLE META_TRANSFER_ACTIONS (
	VERSION_NUMBER VARCHAR(81),
	TRANSFER_ACTION_ID BIGINT,
	COLLECTION_ID BIGINT, 
	COLLECTION_SET_ID BIGINT,
	ACTION_TYPE VARCHAR(81),
	TRANSFER_ACTION_NAME VARCHAR(81),
	ORDER_BY_NO BIGINT,
	DESCRIPTION VARCHAR(81),
	WHERE_CLAUSE_01 VARCHAR(81),
	ACTION_CONTENTS_01 VARCHAR(81),
	ENABLED_FLAG VARCHAR(81),
	CONNECTION_ID BIGINT,
	WHERE_CLAUSE_02 VARCHAR(81),
	WHERE_CLAUSE_03 VARCHAR(81),
	ACTION_CONTENTS_02 VARCHAR(81),
	ACTION_CONTENTS_03 VARCHAR(81)
);
		
