DROP SCHEMA IF EXISTS "SYS" CASCADE;
CREATE SCHEMA "SYS" AUTHORIZATION DBA;
--DROP VIEW SYS.SYSUSERS IF EXISTS;
--DROP VIEW SYS.SYSTABLES IF EXISTS;
--DROP VIEW SYS.SYSCOLUMNS IF EXISTS;
--DROP VIEW SYS.SYSCOLUMN IF EXISTS;

CREATE VIEW
    SYS.SYSUSERS (USER_NAME, USER_ID) AS
SELECT
    UCASE(USER_NAME),
    CASE
        WHEN USER_NAME = 'SA'
        THEN 0
        WHEN USER_NAME = 'dwhrep'
        THEN 1
        WHEN USER_NAME = 'etlrep'
        THEN 2
        WHEN USER_NAME = 'dc'
        THEN 3
        ELSE 4
    END
    CASE AS USER_ID
       FROM
            INFORMATION_SCHEMA.SYSTEM_USERS;

CREATE VIEW
    SYS.SYSTABLES (TABLE_NAME, TABLE_TYPE, TABLE_SCHEMA, CREATOR) AS
SELECT
    TABLE_NAME,
    CASE
        WHEN TABLE_TYPE = 'BASE TABLE'
        THEN 'BASE'
        ELSE TABLE_TYPE
    END CASE AS TABLE_TYPE,
    TABLE_TYPE,
    ( SELECT USER_ID FROM SYS.SYSUSERS WHERE UCASE(USER_NAME) = TABLE_SCHEMA) AS CREATOR
       FROM
            INFORMATION_SCHEMA.TABLES;

CREATE VIEW 
    SYS.SYSCOLUMNS (TNAME, CNAME, COLNO, COLTYPE, LENGTH, SYSLENGTH, NULLS, DEFAULT_VALUE) as
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION,
    CASE
        WHEN DATA_TYPE = 'CHARACTER VARYING' THEN 'VARCHAR'
        ELSE DATA_TYPE
    END CASE AS DATA_TYPE,
    CASE
        WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN CHARACTER_MAXIMUM_LENGTH
        ELSE NUMERIC_PRECISION
    END CASE AS LENGTH,
    NUMERIC_SCALE,
    LEFT(IS_NULLABLE, 1),
    COLUMN_DEFAULT
       FROM
            INFORMATION_SCHEMA.COLUMNS;

CREATE VIEW 
    SYS.SYSCOLUMN (COLUMN_NAME, NULLS) as
SELECT
    COLUMN_NAME,
    LEFT(IS_NULLABLE, 1)
       FROM
            INFORMATION_SCHEMA.COLUMNS;
